# Generated by Django 6.0.3 on 2026-04-11 03:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100)),
                ('objeto_id', models.IntegerField()),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('prefijo_sku', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('codigo_normalizado', models.CharField(blank=True, db_index=True, editable=False, max_length=100)),
                ('tipo_codigo', models.CharField(choices=[('aftermarket', 'General / Comercial'), ('oem', 'Original / Fabricante'), ('interno', 'Interno')], default='aftermarket', max_length=20)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('presentacion_cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('presentacion_unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Código de producto',
                'verbose_name_plural': 'Códigos de producto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FacturaCompraXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso_sri', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de Acceso SRI')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='facturas/xml/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('imagen_factura', models.ImageField(blank=True, null=True, upload_to='facturas/fotos/%Y/%m/')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Proveedor')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='R.U.C.')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de Factura')),
                ('fecha_emision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha Emisión')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Factura')),
                ('clave_acceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de Acceso / Autorización')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carga de Documento (XML/PDF/Foto)',
                'verbose_name_plural': 'Cargas de Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='InventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado'), ('aplicado', 'Aplicado')], default='borrador', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventario físico',
                'verbose_name_plural': 'Inventarios físicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='KitProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador (Dueño)'), ('BODEGA', 'Bodeguero (Maneja IA y Compras)'), ('CAJA', 'Cajera (Maneja OTs y Pagos)')], default='CAJA', max_length=15)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('es_administrador', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='inventario_usuario_groups', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='inventario_usuario_permissions', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'unidad')},
            },
        ),
        migrations.CreateModel(
            name='CatalogoMostrador',
            fields=[
            ],
            options={
                'verbose_name': 'Consulta de Mostrador',
                'verbose_name_plural': 'Consultas de Mostrador',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.codigoproducto',),
        ),
        migrations.CreateModel(
            name='DetalleFacturaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sri', models.CharField(max_length=100)),
                ('descripcion_original', models.CharField(max_length=250, verbose_name='Texto Original (Proveedor)')),
                ('nombre_limpio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Normalizado (Sistema)')),
                ('marca_limpia', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_limpia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingresado_al_inventario', models.BooleanField(default=False)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.facturacompraxml')),
            ],
            options={
                'verbose_name': 'Repuesto en Revisión',
                'verbose_name_plural': 'Repuestos en Revisión',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=100)),
                ('descripcion_proveedor', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_originales', to='inventario.facturacompraxml')),
            ],
            options={
                'verbose_name': 'Detalle Original Proveedor',
                'verbose_name_plural': '📄 1. Detalles Originales (Intocables)',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.codigoproducto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
            },
        ),
        migrations.AddField(
            model_name='codigoproducto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos', to='inventario.marcarepuesto'),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.codigoproducto')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_interno', models.CharField(blank=True, max_length=50, unique=True)),
                ('nombre_base', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('descontinuado', models.BooleanField(default=False)),
                ('datos_incompletos', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['sku_interno'],
            },
        ),
        migrations.CreateModel(
            name='FusionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('producto_duplicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fusiones_duplicado', to='inventario.producto')),
                ('producto_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fusiones_principal', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Fusión de producto',
                'verbose_name_plural': 'Fusiones de producto',
            },
        ),
        migrations.AddField(
            model_name='codigoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventario.codigoproducto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='DetalleInventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField(default=0)),
                ('cantidad_contada', models.IntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('escaneado_por_barcode', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_inventario', to='inventario.codigoproducto')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.inventariofisico')),
            ],
            options={
                'verbose_name': 'Detalle de inventario físico',
                'verbose_name_plural': 'Detalles de inventario físico',
                'unique_together': {('inventario', 'codigo_producto')},
            },
        ),
        migrations.CreateModel(
            name='ComponenteKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes_de_kit', to='inventario.codigoproducto')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='inventario.kitproducto')),
            ],
            options={
                'verbose_name': 'Componente de kit',
                'verbose_name_plural': 'Componentes de kit',
                'unique_together': {('kit', 'codigo_producto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='codigoproducto',
            unique_together={('producto', 'marca', 'codigo')},
        ),
        migrations.CreateModel(
            name='ValorAtributoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_producto', to='inventario.atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Valor de atributo de producto',
                'verbose_name_plural': 'Valores de atributos de producto',
                'unique_together': {('producto', 'atributo')},
            },
        ),
    ]
