# Generated by Django 6.0.3 on 2026-04-12 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompraxml',
            name='dias_plazo',
            field=models.IntegerField(default=0, help_text='Ej: 15, 30 días'),
        ),
        migrations.AddField(
            model_name='facturacompraxml',
            name='esta_pagada',
            field=models.BooleanField(default=False, verbose_name='¿Pagada?'),
        ),
        migrations.AddField(
            model_name='facturacompraxml',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vence el'),
        ),
        migrations.AddField(
            model_name='facturacompraxml',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado (Efectivo/Transf inmediata)'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10),
        ),
        migrations.AddField(
            model_name='facturacompraxml',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facturacompraxml',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facturacompraxml',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facturacompraxml',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Emisión'),
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('comprobante_banco', models.CharField(blank=True, help_text='N° de Operación o Cheque', max_length=100)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='inventario.facturacompraxml')),
            ],
            options={
                'verbose_name': 'Abono a Proveedor',
                'verbose_name_plural': 'Abonos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
