# Generated by Django 6.0.3 on 2026-04-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_facturacompraxml_dias_plazo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefacturaoriginal',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detallefacturatemporal',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='pagoproveedor',
            name='factura',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='DetalleFacturaOriginal',
        ),
        migrations.DeleteModel(
            name='DetalleFacturaTemporal',
        ),
        migrations.DeleteModel(
            name='FacturaCompraXML',
        ),
        migrations.DeleteModel(
            name='PagoProveedor',
        ),
    ]
