# Generated by Django 6.0.3 on 2026-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_detallefacturaoriginal_factura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='componentekit',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleinventariofisico',
            name='cantidad_contada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleinventariofisico',
            name='stock_sistema',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
