# Generated by Django 6.0 on 2026-04-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_usuario_options_alter_componentekit_cantidad_and_more'),
        ('ordenes_de_trabajo', '0012_alter_ordentrabajo_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puede_cambiar_sucursal',
            field=models.BooleanField(default=False, help_text='Permite cambiar la sucursal activa de trabajo. Útil para administradores.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal base del usuario. Para usuarios normales se usa automáticamente al crear OTs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='ordenes_de_trabajo.sucursal'),
        ),
    ]
