# Generated by Django 6.0 on 2026-04-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_usuario_puede_cambiar_sucursal_usuario_sucursal'),
        ('ordenes_de_trabajo', '0012_alter_ordentrabajo_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock por sucursal',
                'verbose_name_plural': 'Stocks por sucursal',
                'ordering': ['codigo_producto__codigo', 'sucursal__codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='codigo_producto',
        ),
        migrations.AddField(
            model_name='inventariofisico',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_fisicos', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['sucursal', 'fecha'], name='inventario__sucursa_f0bc11_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['codigo_producto', 'fecha'], name='inventario__codigo__d679d5_idx'),
        ),
        migrations.AddField(
            model_name='stocksucursal',
            name='codigo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_por_sucursal', to='inventario.codigoproducto'),
        ),
        migrations.AddField(
            model_name='stocksucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddIndex(
            model_name='stocksucursal',
            index=models.Index(fields=['sucursal', 'codigo_producto'], name='inventario__sucursa_9133dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksucursal',
            unique_together={('codigo_producto', 'sucursal')},
        ),
    ]
