# Generated by Django 6.0 on 2026-04-21 19:11

import inventario.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_stocksucursal_remove_stock_codigo_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', inventario.models.UsuarioManager()),
            ],
        ),
    ]
