# Generated by Django 6.0 on 2026-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='origen',
            field=models.CharField(choices=[('BODEGA', 'Ingreso formal en Bodega'), ('MOSTRADOR', 'Creación rápida al vuelo')], default='BODEGA', help_text='Indica si nació por compra formal o de urgencia en el mostrador.', max_length=20),
        ),
        migrations.AlterField(
            model_name='codigoproducto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Puede quedar vacío si el producto se creó rápido sin escanear.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='datos_incompletos',
            field=models.BooleanField(default=False, help_text='El bodeguero debe revisar esto (ej. asignar marca o proveedor real).'),
        ),
    ]
