# Generated by Django 6.0.3 on 2026-05-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_producto_origen_alter_codigoproducto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoproducto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Puede quedar vacío si el producto se creó rápido sin escanear.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='datos_incompletos',
            field=models.BooleanField(default=False, help_text='El bodeguero debe revisar esto.'),
        ),
    ]
