# Generated by Django 6.0.3 on 2026-06-05 04:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0010_alter_componentekit_cantidad_and_more'),
        ('ordenes_de_trabajo', '0045_configuraciontributaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoproducto',
            name='margen_ganancia_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='codigoproducto',
            name='porcentaje_iva_costo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='codigoproducto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='datos_incompletos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='origen',
            field=models.CharField(choices=[('BODEGA', 'Ingreso formal en Bodega'), ('MOSTRADOR', 'Creación rápida al vuelo')], default='BODEGA', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='inventario_usuario_groups', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puede_cambiar_sucursal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='inventario_usuario_permissions', to='auth.permission', verbose_name='permisos de usuario'),
        ),
    ]
