# Generated by Django 6.0.3 on 2026-06-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_codigoproducto_margen_ganancia_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='codigo_producto',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.producto'),
        ),
    ]
