# Generated by Django 6.0.3 on 2026-07-13 05:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_cuotapago_alter_detallefacturaoriginal_options_and_more'),
        ('inventario', '0012_remove_imagenproducto_codigo_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprendizajeProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('FACTURA', 'Factura de compra'), ('MANUAL', 'Creación manual'), ('CORRECCION', 'Corrección de usuario'), ('IMPORTACION', 'Importación'), ('OTRO', 'Otro')], default='FACTURA', max_length=20)),
                ('texto_original', models.TextField(help_text='Descripción exactamente como fue recibida. No debe sobrescribirse con el nombre limpio.')),
                ('texto_normalizado', models.TextField(blank=True, db_index=True, editable=False)),
                ('codigo_original', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_normalizado', models.CharField(blank=True, db_index=True, editable=False, max_length=150)),
                ('veces_confirmado', models.PositiveIntegerField(default=1)),
                ('confianza_acumulada', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Indicador histórico de confianza. No representa necesariamente una probabilidad matemática.', max_digits=7)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ultima_confirmacion_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('categoria_confirmada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprendizajes_confirmados', to='inventario.categoria')),
                ('codigo_producto_confirmado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_confirmados', to='inventario.codigoproducto')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_producto_confirmados', to=settings.AUTH_USER_MODEL)),
                ('detalle_original', models.ForeignKey(blank=True, help_text='Detalle original e inmutable de la factura que originó este aprendizaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_producto', to='compras.detallefacturaoriginal')),
                ('marca_confirmada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_confirmados', to='inventario.marcarepuesto')),
                ('producto_confirmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes_confirmados', to='inventario.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_producto', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Aprendizaje de producto',
                'verbose_name_plural': 'Aprendizajes de productos',
                'ordering': ['-veces_confirmado', '-ultima_confirmacion_en'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('FACTURA', 'Factura de compra'), ('PRODUCTO', 'Creación individual de producto'), ('CODIGO', 'Creación individual de código'), ('IMPORTACION', 'Importación'), ('OTRO', 'Otro')], default='FACTURA', max_length=20)),
                ('texto_entrada', models.TextField()),
                ('texto_normalizado', models.TextField(blank=True, db_index=True, editable=False)),
                ('codigo_entrada', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_normalizado', models.CharField(blank=True, db_index=True, editable=False, max_length=150)),
                ('confianza', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('puntaje_codigo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('puntaje_texto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('puntaje_historial_compras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('puntaje_aprendizaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('puntaje_proveedor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada'), ('CORREGIDA', 'Corregida'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_revision', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria_confirmada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_confirmadas', to='inventario.categoria')),
                ('categoria_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_recibidas', to='inventario.categoria')),
                ('codigo_producto_confirmado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_confirmadas', to='inventario.codigoproducto')),
                ('codigo_producto_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_recibidas', to='inventario.codigoproducto')),
                ('detalle_original', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugerencia_producto', to='compras.detallefacturaoriginal')),
                ('marca_confirmada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_confirmadas', to='inventario.marcarepuesto')),
                ('marca_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_recibidas', to='inventario.marcarepuesto')),
                ('producto_confirmado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_confirmadas', to='inventario.producto')),
                ('producto_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_recibidas', to='inventario.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_producto', to='compras.proveedor')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_producto_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia de producto',
                'verbose_name_plural': 'Sugerencias de productos',
                'ordering': ['estado', '-confianza', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaSugerenciaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CODIGO_EXACTO', 'Código exacto'), ('CODIGO_SIMILAR', 'Código similar'), ('TEXTO_PRODUCTO', 'Texto de producto'), ('NOMBRE_COMERCIAL', 'Nombre comercial'), ('HISTORIAL_COMPRA', 'Historial de compras'), ('MISMO_PROVEEDOR', 'Mismo proveedor'), ('APRENDIZAJE', 'Aprendizaje confirmado'), ('CATEGORIA', 'Coincidencia de categoría'), ('MARCA', 'Coincidencia de marca'), ('OTRO', 'Otro')], max_length=30)),
                ('texto_comparado', models.TextField(blank=True, null=True)),
                ('codigo_comparado', models.CharField(blank=True, max_length=150, null=True)),
                ('puntaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Peso aplicado por el motor de sugerencias.', max_digits=5)),
                ('puntaje_ponderado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=8)),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprendizaje_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_generadas', to='inventario.aprendizajeproducto')),
                ('codigo_producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_sugerencias', to='inventario.codigoproducto')),
                ('detalle_compra_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_sugerencias', to='compras.detallefacturaoriginal')),
                ('producto_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_sugerencias', to='inventario.producto')),
                ('sugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='inventario.sugerenciaproducto')),
            ],
            options={
                'verbose_name': 'Evidencia de sugerencia',
                'verbose_name_plural': 'Evidencias de sugerencias',
                'ordering': ['-puntaje_ponderado', '-puntaje', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aprendizajeproducto',
            index=models.Index(fields=['codigo_normalizado', 'proveedor'], name='inventario__codigo__e07f66_idx'),
        ),
        migrations.AddIndex(
            model_name='aprendizajeproducto',
            index=models.Index(fields=['texto_normalizado'], name='inventario__texto_n_8bff44_idx'),
        ),
        migrations.AddIndex(
            model_name='aprendizajeproducto',
            index=models.Index(fields=['producto_confirmado', 'activo'], name='inventario__product_a29db4_idx'),
        ),
        migrations.AddIndex(
            model_name='aprendizajeproducto',
            index=models.Index(fields=['categoria_confirmada', 'activo'], name='inventario__categor_d121da_idx'),
        ),
        migrations.AddIndex(
            model_name='aprendizajeproducto',
            index=models.Index(fields=['origen', 'activo'], name='inventario__origen_9258ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='aprendizajeproducto',
            constraint=models.CheckConstraint(condition=models.Q(('veces_confirmado__gte', 1)), name='inventario_aprendizaje_veces_confirmado_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='aprendizajeproducto',
            constraint=models.CheckConstraint(condition=models.Q(('confianza_acumulada__gte', 0), ('confianza_acumulada__lte', 100)), name='inventario_aprendizaje_confianza_entre_0_y_100'),
        ),
        migrations.AddIndex(
            model_name='sugerenciaproducto',
            index=models.Index(fields=['estado', 'confianza'], name='inventario__estado_d320e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sugerenciaproducto',
            index=models.Index(fields=['codigo_normalizado', 'proveedor'], name='inventario__codigo__27911a_idx'),
        ),
        migrations.AddIndex(
            model_name='sugerenciaproducto',
            index=models.Index(fields=['producto_sugerido', 'estado'], name='inventario__product_fdd2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sugerenciaproducto',
            index=models.Index(fields=['categoria_sugerida', 'estado'], name='inventario__categor_8c9f52_idx'),
        ),
        migrations.AddIndex(
            model_name='sugerenciaproducto',
            index=models.Index(fields=['origen', 'estado'], name='inventario__origen_7c54ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='sugerenciaproducto',
            constraint=models.CheckConstraint(condition=models.Q(('confianza__gte', 0), ('confianza__lte', 100)), name='inventario_sugerencia_confianza_entre_0_y_100'),
        ),
        migrations.AddIndex(
            model_name='evidenciasugerenciaproducto',
            index=models.Index(fields=['sugerencia', 'tipo'], name='inventario__sugeren_49fd77_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciasugerenciaproducto',
            index=models.Index(fields=['tipo', 'puntaje'], name='inventario__tipo_762343_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciasugerenciaproducto',
            index=models.Index(fields=['producto_fuente'], name='inventario__product_c8fd62_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciasugerenciaproducto',
            index=models.Index(fields=['aprendizaje_fuente'], name='inventario__aprendi_86f272_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenciasugerenciaproducto',
            constraint=models.CheckConstraint(condition=models.Q(('puntaje__gte', 0), ('puntaje__lte', 100)), name='inventario_evidencia_puntaje_entre_0_y_100'),
        ),
        migrations.AddConstraint(
            model_name='evidenciasugerenciaproducto',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gte', 0)), name='inventario_evidencia_peso_no_negativo'),
        ),
    ]
