# Generated by Django 6.0.3 on 2026-07-13 06:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_cuotapago_alter_detallefacturaoriginal_options_and_more'),
        ('inventario', '0013_aprendizajeproducto_sugerenciaproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_original', models.CharField(help_text='Forma real en que apareció el producto. Ejemplo: CABIN FILTER, FILT HABITÁCULO o 10W30.', max_length=255)),
                ('alias_normalizado', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('origen', models.CharField(choices=[('MANUAL', 'Registrado manualmente'), ('FACTURA', 'Obtenido de factura'), ('APRENDIZAJE', 'Generado por aprendizaje'), ('IMPORTACION', 'Importación')], db_index=True, default='MANUAL', max_length=20)),
                ('veces_confirmado', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alias de producto',
                'verbose_name_plural': 'Alias de productos',
                'ordering': ['-veces_confirmado', 'alias_normalizado'],
            },
        ),
        migrations.RemoveIndex(
            model_name='evidenciasugerenciaproducto',
            name='inventario__sugeren_49fd77_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidenciasugerenciaproducto',
            name='inventario__tipo_762343_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidenciasugerenciaproducto',
            name='inventario__product_c8fd62_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidenciasugerenciaproducto',
            name='inventario__aprendi_86f272_idx',
        ),
        migrations.RemoveConstraint(
            model_name='evidenciasugerenciaproducto',
            name='inventario_evidencia_puntaje_entre_0_y_100',
        ),
        migrations.RemoveConstraint(
            model_name='evidenciasugerenciaproducto',
            name='inventario_evidencia_peso_no_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='aprendizajeproducto',
            name='inventario_aprendizaje_veces_confirmado_mayor_cero',
        ),
        migrations.RemoveConstraint(
            model_name='aprendizajeproducto',
            name='inventario_aprendizaje_confianza_entre_0_y_100',
        ),
        migrations.RemoveConstraint(
            model_name='sugerenciaproducto',
            name='inventario_sugerencia_confianza_entre_0_y_100',
        ),
        migrations.RemoveIndex(
            model_name='aprendizajeproducto',
            name='inventario__codigo__e07f66_idx',
        ),
        migrations.RemoveIndex(
            model_name='aprendizajeproducto',
            name='inventario__texto_n_8bff44_idx',
        ),
        migrations.RemoveIndex(
            model_name='aprendizajeproducto',
            name='inventario__origen_9258ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='sugerenciaproducto',
            name='inventario__product_fdd2a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='sugerenciaproducto',
            name='inventario__categor_8c9f52_idx',
        ),
        migrations.RenameField(
            model_name='sugerenciaproducto',
            old_name='puntaje_historial_compras',
            new_name='puntaje_alias',
        ),
        migrations.AddField(
            model_name='aprendizajeproducto',
            name='confianza_promedio',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='detalle_origen_creacion',
            field=models.ForeignKey(blank=True, help_text='Detalle original de la factura que dio origen a la creación del producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to='compras.detallefacturaoriginal'),
        ),
        migrations.AddField(
            model_name='sugerenciaproducto',
            name='puntaje_compras',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='aprendizajeproducto',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aprendizajeproducto',
            name='detalle_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_producto', to='compras.detallefacturaoriginal'),
        ),
        migrations.AlterField(
            model_name='aprendizajeproducto',
            name='origen',
            field=models.CharField(choices=[('FACTURA', 'Factura de compra'), ('INDIVIDUAL', 'Creación individual'), ('MOSTRADOR', 'Creación rápida'), ('CORRECCION', 'Corrección de usuario'), ('IMPORTACION', 'Importación')], db_index=True, default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='aprendizajeproducto',
            name='texto_original',
            field=models.TextField(help_text='Texto original que fue confirmado. No se debe sobrescribir con el nombre limpio.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='datos_incompletos',
            field=models.BooleanField(default=False, help_text='Indica que el producto fue creado rápidamente y todavía requiere revisión.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='origen',
            field=models.CharField(choices=[('INDIVIDUAL', 'Creación individual desde inventario'), ('FACTURA', 'Creado desde factura de compra'), ('MOSTRADOR', 'Creación rápida desde mostrador')], db_index=True, default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sugerenciaproducto',
            name='detalle_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_producto', to='compras.detallefacturaoriginal'),
        ),
        migrations.AlterField(
            model_name='sugerenciaproducto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CORREGIDA', 'Corregida'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sugerenciaproducto',
            name='origen',
            field=models.CharField(choices=[('FACTURA', 'Factura de compra'), ('INDIVIDUAL', 'Creación individual'), ('CODIGO', 'Creación de código'), ('MOSTRADOR', 'Creación rápida'), ('IMPORTACION', 'Importación')], db_index=True, default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sugerenciaproducto',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aprendizajeproducto',
            index=models.Index(fields=['codigo_normalizado', 'proveedor', 'activo'], name='inventario__codigo__b01f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='aprendizajeproducto',
            index=models.Index(fields=['texto_normalizado', 'activo'], name='inventario__texto_n_b110a4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='inventario__categor_c6db1b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['origen', 'activo'], name='inventario__origen_011230_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre_base'], name='inventario__nombre__005d95_idx'),
        ),
        migrations.AddIndex(
            model_name='sugerenciaproducto',
            index=models.Index(fields=['texto_normalizado', 'estado'], name='inventario__texto_n_45ee5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='aprendizajeproducto',
            constraint=models.CheckConstraint(condition=models.Q(('veces_confirmado__gte', 1)), name='inventario_aprendizaje_confirmaciones_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='aprendizajeproducto',
            constraint=models.CheckConstraint(condition=models.Q(('confianza_promedio__gte', 0), ('confianza_promedio__lte', 100)), name='inventario_aprendizaje_confianza_valida'),
        ),
        migrations.AddConstraint(
            model_name='sugerenciaproducto',
            constraint=models.CheckConstraint(condition=models.Q(('confianza__gte', 0), ('confianza__lte', 100)), name='inventario_sugerencia_confianza_valida'),
        ),
        migrations.AddField(
            model_name='aliasproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alias_productos', to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='aliasproducto',
            name='codigo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias', to='inventario.codigoproducto'),
        ),
        migrations.AddField(
            model_name='aliasproducto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_productos', to='inventario.marcarepuesto'),
        ),
        migrations.AddField(
            model_name='aliasproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='inventario.producto'),
        ),
        migrations.RemoveField(
            model_name='evidenciasugerenciaproducto',
            name='aprendizaje_fuente',
        ),
        migrations.RemoveField(
            model_name='evidenciasugerenciaproducto',
            name='codigo_producto_fuente',
        ),
        migrations.RemoveField(
            model_name='evidenciasugerenciaproducto',
            name='detalle_compra_fuente',
        ),
        migrations.RemoveField(
            model_name='evidenciasugerenciaproducto',
            name='producto_fuente',
        ),
        migrations.RemoveField(
            model_name='evidenciasugerenciaproducto',
            name='sugerencia',
        ),
        migrations.RemoveField(
            model_name='aprendizajeproducto',
            name='confianza_acumulada',
        ),
        migrations.AddIndex(
            model_name='aliasproducto',
            index=models.Index(fields=['alias_normalizado', 'activo'], name='inventario__alias_n_1009f6_idx'),
        ),
        migrations.AddIndex(
            model_name='aliasproducto',
            index=models.Index(fields=['producto', 'activo'], name='inventario__product_9fa2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='aliasproducto',
            index=models.Index(fields=['categoria', 'activo'], name='inventario__categor_6a34ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='aliasproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'alias_normalizado'), name='inventario_alias_unico_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='aliasproducto',
            constraint=models.CheckConstraint(condition=models.Q(('veces_confirmado__gte', 1)), name='inventario_alias_confirmaciones_mayor_cero'),
        ),
        migrations.DeleteModel(
            name='EvidenciaSugerenciaProducto',
        ),
    ]
