# Generated by Django 6.0.3 on 2026-07-19 01:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_aliasproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerenciaproducto',
            name='puntaje_categoria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='sugerenciaproducto',
            name='texto_entrada',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TerminoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('SINONIMO', 'Sinónimo')], default='POSITIVO', max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminos_clasificacion', to='inventario.categoria')),
            ],
            options={
                'ordering': ['categoria', 'termino'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'termino', 'tipo'), name='termino_categoria_unico')],
            },
        ),
    ]
