# Generated by Django 6.0.3 on 2026-08-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_sugerenciaproducto_puntaje_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Bodeguero'), ('CAJA', 'Cajera'), ('TECNICO', 'Técnico')], default='CAJA', max_length=15),
        ),
    ]
