# Generated by Django 6.0.3 on 2026-08-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerido', models.BooleanField(default=False, help_text='Indica si este atributo debe completarse obligatoriamente para productos de esta categoría.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que debe aparecer el atributo dentro del formulario.')),
                ('activo', models.BooleanField(default=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_configuradas', to='inventario.atributo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_configurados', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Atributo de categoría',
                'verbose_name_plural': 'Atributos de categorías',
                'ordering': ['orden', 'atributo__nombre'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='inventario__categor_19b12d_idx')],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'atributo'), name='categoria_atributo_unico')],
            },
        ),
    ]
