# Generated by Django 6.0.3 on 2026-08-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_categoriaatributo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('cambiar_sucursal_operativa', 'Cambiar sucursal operativa')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puede_cambiar_sucursal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
