# Generated by Django 6.0.3 on 2026-08-19 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias_productos/'),
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='familias_productos/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Familia de producto',
                'verbose_name_plural': 'Familias de productos',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'orden'], name='inventario__activo_8918f4_idx')],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='inventario.familiaproducto'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['familia', 'nombre'], name='inventario__familia_f12423_idx'),
        ),
    ]
