# Generated by Django 6.0.3 on 2026-08-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_categoria_imagen_familiaproducto_categoria_familia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='familiaproducto',
            name='imagen',
        ),
    ]
