# Generated by Django 6.0.3 on 2026-08-19 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_remove_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='tipo_dato',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('ENTERO', 'Número entero'), ('DECIMAL', 'Número decimal'), ('BOOLEANO', 'Sí / No'), ('OPCION', 'Lista de opciones')], default='TEXTO', max_length=20),
        ),
        migrations.CreateModel(
            name='OpcionCategoriaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='inventario.categoriaatributo')),
            ],
            options={
                'verbose_name': 'Opción de atributo',
                'verbose_name_plural': 'Opciones de atributos',
                'ordering': ['orden', 'valor'],
                'indexes': [models.Index(fields=['categoria_atributo', 'activo'], name='inventario__categor_0f19d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('categoria_atributo', 'valor'), name='opcion_categoria_atributo_unica')],
            },
        ),
    ]
