# Generated by Django 6.0.3 on 2026-08-21 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAccesoAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_acceso_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de acceso a MAO Asistente',
                'verbose_name_plural': 'Códigos de acceso a MAO Asistente',
                'ordering': ['-creado_en'],
            },
        ),
    ]
