# Generated by Django 6.0.3 on 2026-08-22 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
        ('ordenes_de_trabajo', '0051_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoaccesoasistente',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_acceso_asistente', to='ordenes_de_trabajo.sucursal'),
        ),
    ]
