# Generated by Django 6.0.3 on 2026-04-11 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('C', 'Cédula'), ('R', 'RUC'), ('P', 'Pasaporte')], default='C', max_length=1)),
                ('identificacion', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Cédula/RUC')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MEC', 'Mecánica'), ('PIN', 'Pintura'), ('END', 'Enderezada'), ('ELE', 'Electricidad'), ('EXT', 'Trabajo Externo')], max_length=3)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_sugerido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Catálogo de Servicio',
                'verbose_name_plural': 'Catálogo de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('cliente_respaldo', models.CharField(blank=True, db_column='cliente', max_length=200, null=True, verbose_name='Nombre Cliente (Historial)')),
                ('placa', models.CharField(max_length=15)),
                ('vehiculo', models.CharField(blank=True, max_length=150, null=True)),
                ('anio_vehiculo', models.CharField(blank=True, max_length=4, null=True)),
                ('kilometraje', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_recepcion', models.TextField(blank=True, null=True)),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'En Taller / Abierta'), ('ESPERA_REP', 'Esperando Repuestos'), ('TRABAJO_EXT', 'Trabajo Externo'), ('TERMINADA', 'Trabajo Terminado'), ('CERRADA', 'Entregado / Pagada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=15)),
                ('fecha_ingreso', models.DateTimeField()),
                ('total_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='ordenes_de_trabajo.cliente')),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='OrdenInsumoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.codigoproducto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalles', to='ordenes_de_trabajo.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_detalles', to='ordenes_de_trabajo.ordentrabajo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes_de_trabajo.serviciocatalogo')),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes_de_trabajo.tecnico')),
            ],
        ),
    ]
