# Generated by Django 6.0 on 2026-04-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='checklist_confirmado_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='color_hex',
            field=models.CharField(default='#1d1d1f', help_text='Código hexadecimal del color para el Dashboard (ej. #FF0000 para rojo).', max_length=7),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='nivel_combustible',
            field=models.CharField(blank=True, choices=[('E', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('F', 'Lleno')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sintomas_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='trabajos_solicitados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='anio_vehiculo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente_respaldo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Cliente (Historial)'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='placa',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.CreateModel(
            name='FotoRecepcionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes/recepcion/')),
                ('tipo_foto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_recepcion', to='ordenes_de_trabajo.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenChecklistRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.BooleanField(default=False)),
                ('plumas', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('pantalla', models.BooleanField(default=False)),
                ('tuerca_seguridad', models.BooleanField(default=False)),
                ('encendedor_cig', models.BooleanField(default=False)),
                ('triangulos', models.BooleanField(default=False)),
                ('gata', models.BooleanField(default=False)),
                ('herramientas', models.BooleanField(default=False)),
                ('llanta_emergencia', models.BooleanField(default=False)),
                ('faros_lunas', models.BooleanField(default=False)),
                ('tapacubos', models.BooleanField(default=False)),
                ('antena', models.BooleanField(default=False)),
                ('adicionales_reportados', models.TextField(blank=True, null=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_recepcion', to='ordenes_de_trabajo.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDanioVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_danio', models.CharField(choices=[('GOLPE', 'Golpe'), ('RAYON', 'Rayón'), ('TRIZADO', 'Trizado'), ('OTRO', 'Otro')], max_length=10)),
                ('vista', models.CharField(choices=[('SUPERIOR', 'Superior'), ('LATERAL_IZQ', 'Lateral izquierda'), ('LATERAL_DER', 'Lateral derecha'), ('FRONTAL', 'Frontal'), ('TRASERA', 'Trasera')], default='SUPERIOR', max_length=20)),
                ('x', models.DecimalField(decimal_places=2, max_digits=6)),
                ('y', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danios_vehiculo', to='ordenes_de_trabajo.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenObjetoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_adicionales', to='ordenes_de_trabajo.ordentrabajo')),
            ],
        ),
    ]
