# Generated by Django 6.0 on 2026-04-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0002_ordentrabajo_checklist_confirmado_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCroquisDanio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(default='GENERAL', max_length=20)),
                ('trazos', models.JSONField(blank=True, default=list, help_text='Lista de trazos dibujados en el croquis')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ordenes/croquis/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='croquis_danios', to='ordenes_de_trabajo.ordentrabajo')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdenDanioVehiculo',
        ),
    ]
