# Generated by Django 6.0 on 2026-04-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0003_ordencroquisdanio_delete_ordendaniovehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencroquisdanio',
            options={'verbose_name': 'Croquis de daño', 'verbose_name_plural': 'Croquis de daños'},
        ),
        migrations.RenameField(
            model_name='ordencroquisdanio',
            old_name='actualizado_en',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='ordencroquisdanio',
            old_name='imagen',
            new_name='imagen_generada',
        ),
        migrations.RemoveField(
            model_name='ordencroquisdanio',
            name='vista',
        ),
        migrations.AddField(
            model_name='ordencroquisdanio',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordencroquisdanio',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='croquis_danio', to='ordenes_de_trabajo.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='ordencroquisdanio',
            name='trazos',
            field=models.JSONField(blank=True, default=list, help_text='Trazo libre dibujado sobre la plantilla del vehículo.'),
        ),
    ]
