# Generated by Django 6.0 on 2026-04-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0004_alter_ordencroquisdanio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoRecepcionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Trabajo sugerido de recepción',
                'verbose_name_plural': 'Trabajos sugeridos de recepción',
                'ordering': ['orden_visual', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='sintomas_cliente',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='trabajos_solicitados',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='proximo_mantenimiento_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrdenSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas_items', to='ordenes_de_trabajo.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Síntoma de cliente',
                'verbose_name_plural': 'Síntomas de cliente',
                'ordering': ['orden_item'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_solicitados_items', to='ordenes_de_trabajo.ordentrabajo')),
                ('trabajo_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes_de_trabajo.trabajorecepcioncatalogo')),
            ],
            options={
                'verbose_name': 'Trabajo solicitado',
                'verbose_name_plural': 'Trabajos solicitados',
                'ordering': ['orden_item'],
            },
        ),
    ]
