# Generated by Django 6.0.3 on 2026-04-18 05:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0005_trabajorecepcioncatalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='fotorecepcionvehiculo',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Foto de recepción', 'verbose_name_plural': 'Fotos de recepción'},
        ),
        migrations.AlterModelOptions(
            name='ordenchecklistrecepcion',
            options={'verbose_name': 'Checklist de recepción', 'verbose_name_plural': 'Checklists de recepción'},
        ),
        migrations.AlterModelOptions(
            name='ordeninsumodetalle',
            options={'ordering': ['orden_item', 'id'], 'verbose_name': 'Detalle de insumo', 'verbose_name_plural': 'Detalles de insumos'},
        ),
        migrations.AlterModelOptions(
            name='ordenobjetoadicional',
            options={'ordering': ['id'], 'verbose_name': 'Objeto adicional', 'verbose_name_plural': 'Objetos adicionales'},
        ),
        migrations.AlterModelOptions(
            name='ordenserviciodetalle',
            options={'ordering': ['orden_item', 'id'], 'verbose_name': 'Detalle de servicio', 'verbose_name_plural': 'Detalles de servicios'},
        ),
        migrations.AlterModelOptions(
            name='ordensintoma',
            options={'ordering': ['orden_item', 'id'], 'verbose_name': 'Síntoma de cliente', 'verbose_name_plural': 'Síntomas de cliente'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajosolicitado',
            options={'ordering': ['orden_item', 'id'], 'verbose_name': 'Trabajo solicitado', 'verbose_name_plural': 'Trabajos solicitados'},
        ),
        migrations.AlterModelOptions(
            name='serviciocatalogo',
            options={'ordering': ['categoria', 'descripcion'], 'verbose_name': 'Catálogo de Servicio', 'verbose_name_plural': 'Catálogo de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['nombre'], 'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='orden_item',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='orden_item',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordeninsumodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
