# Generated by Django 6.0 on 2026-04-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0006_alter_cliente_options_and_more'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenserviciodetalle',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_detalle', to='servicios.serviciocatalogo'),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='descripcion_servicio',
            field=models.CharField(blank=True, default='', help_text='Descripción congelada del servicio al momento de guardar la OT.', max_length=255),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='tipo_tarifa_aplicada',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('AUTO', 'Auto'), ('AUTO_3P', 'Auto 3 puertas'), ('AUTO_5P', 'Auto 5 puertas'), ('SUV_3P', 'SUV 3 puertas'), ('SUV_5P', 'SUV 5 puertas'), ('CAMIONETA_CS', 'Camioneta cabina sencilla'), ('CAMIONETA_DC', 'Camioneta doble cabina'), ('CAMIONETA_GRANDE', 'Camioneta grande')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='variante_precio_aplicada',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('REPINTADO', 'Repintado'), ('NUEVO', 'Nuevo'), ('TRICAPA', 'Tricapa / Candys'), ('ESPECIAL', 'Color especial')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sintomas_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_tarifa_vehiculo',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('AUTO', 'Auto'), ('AUTO_3P', 'Auto 3 puertas'), ('AUTO_5P', 'Auto 5 puertas'), ('SUV_3P', 'SUV 3 puertas'), ('SUV_5P', 'SUV 5 puertas'), ('CAMIONETA_CS', 'Camioneta cabina sencilla'), ('CAMIONETA_DC', 'Camioneta doble cabina'), ('CAMIONETA_GRANDE', 'Camioneta grande')], default='NO_APLICA', help_text='Clasificación usada para sugerir mano de obra o pintura.', max_length=20),
        ),
        migrations.DeleteModel(
            name='ServicioCatalogo',
        ),
    ]
