# Generated by Django 6.0.3 on 2026-04-19 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0007_alter_ordenserviciodetalle_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenInsumoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_original', models.CharField(max_length=255)),
                ('codigo_original', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('requiere_revision', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Insumo histórico migrado',
                'verbose_name_plural': 'Insumos históricos migrados',
                'ordering': ['orden_item', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MO', 'Mano de obra'), ('MOE', 'Mano de obra externa')], max_length=3)),
                ('descripcion_original', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('es_cortesia', models.BooleanField(default=False)),
                ('orden_item', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Servicio histórico migrado',
                'verbose_name_plural': 'Servicios históricos migrados',
                'ordering': ['tipo', 'orden_item', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='anio_origen_migracion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Año/lote del archivo histórico desde donde se migró.', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='archivo_origen',
            field=models.CharField(blank=True, help_text='Nombre del archivo fuente de la migración.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='es_migrada',
            field=models.BooleanField(default=False, help_text='Indica si esta OT fue extraída/migrada desde archivos históricos.'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='hoja_origen',
            field=models.CharField(blank=True, help_text='Hoja origen dentro del archivo histórico.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='json_origen',
            field=models.JSONField(blank=True, help_text='JSON original estructurado usado para la migración.', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='numero_orden_origen',
            field=models.CharField(blank=True, help_text='Número original encontrado en el archivo histórico.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='requiere_revision_migracion',
            field=models.BooleanField(default=False, help_text='Marcar en True si la OT migrada tiene datos ambiguos o incompletos.'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_receptor',
            field=models.ForeignKey(blank=True, help_text='Puede quedar vacío en OT históricas migradas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre_completo'], name='ordenes_de__nombre__4654b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['placa', 'fecha_ingreso'], name='ordenes_de__placa_fde4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado', 'fecha_ingreso'], name='ordenes_de__estado_cfad4a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['es_migrada', 'anio_origen_migracion'], name='ordenes_de__es_migr_2ad10a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['numero_orden_origen'], name='ordenes_de__numero__86f985_idx'),
        ),
        migrations.AddField(
            model_name='ordeninsumohistorico',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_historicos', to='ordenes_de_trabajo.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='ordenserviciohistorico',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_historicos', to='ordenes_de_trabajo.ordentrabajo'),
        ),
    ]
