# Generated by Django 6.0.3 on 2026-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0008_ordeninsumohistorico_ordenserviciohistorico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='hash_migracion',
            field=models.CharField(blank=True, db_index=True, help_text='Hash del JSON importado para detectar duplicados reales.', max_length=64, null=True),
        ),
    ]
