# Generated by Django 6.0.3 on 2026-04-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0009_ordentrabajo_hash_migracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeninsumohistorico',
            name='descripcion_original',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordenserviciohistorico',
            name='descripcion_original',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='anio_origen_migracion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='archivo_origen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente_respaldo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='color_hex',
            field=models.CharField(default='#1d1d1f', max_length=7),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='es_migrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='hoja_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='json_origen',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero_orden_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='requiere_revision_migracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo_tarifa_vehiculo',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('AUTO', 'Auto'), ('AUTO_3P', 'Auto 3 puertas'), ('AUTO_5P', 'Auto 5 puertas'), ('SUV_3P', 'SUV 3 puertas'), ('SUV_5P', 'SUV 5 puertas'), ('CAMIONETA_CS', 'Camioneta cabina sencilla'), ('CAMIONETA_DC', 'Camioneta doble cabina'), ('CAMIONETA_GRANDE', 'Camioneta grande')], default='NO_APLICA', max_length=20),
        ),
    ]
