# Generated by Django 6.0 on 2026-04-20 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0010_alter_ordeninsumohistorico_descripcion_original_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_origen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='placa',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ExpedienteVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_respaldo', models.CharField(blank=True, max_length=200, null=True)),
                ('placa', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=150, null=True)),
                ('anio_vehiculo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='ordenes_de_trabajo.cliente')),
            ],
            options={
                'verbose_name': 'Expediente de vehículo',
                'verbose_name_plural': 'Expedientes de vehículos',
                'ordering': ['placa', 'vehiculo', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='ordenes_de_trabajo.expedientevehiculo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['sucursal', 'estado'], name='ordenes_de__sucursa_fbee00_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['fecha_origen'], name='ordenes_de__fecha_o_61b3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientevehiculo',
            index=models.Index(fields=['placa'], name='ordenes_de__placa_eb0881_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientevehiculo',
            index=models.Index(fields=['vehiculo'], name='ordenes_de__vehicul_3c3f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientevehiculo',
            index=models.Index(fields=['cliente_respaldo'], name='ordenes_de__cliente_7c195f_idx'),
        ),
    ]
