# Generated by Django 6.0.3 on 2026-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0012_alter_ordentrabajo_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='descripcion_factura',
            field=models.CharField(blank=True, help_text='Lo que aparecerá impreso en la proforma/factura. Se auto-llena con el nombre del producto si se deja en blanco.', max_length=255, verbose_name='Descripción para el Cliente'),
        ),
    ]
