# Generated by Django 6.0 on 2026-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0013_ordeninsumodetalle_descripcion_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='firma_cliente',
            field=models.ImageField(blank=True, help_text='Imagen de la firma digital del cliente.', null=True, upload_to='ordenes/firmas/%Y/%m/'),
        ),
    ]
