# Generated by Django 6.0.3 on 2026-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0014_ordentrabajo_fecha_firma_ordentrabajo_firma_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'En Taller / Abierta'), ('CERRADA', 'Entregado / Pagada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=15),
        ),
    ]
