# Generated by Django 6.0.3 on 2026-04-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresaemisora_porcentaje_iva'),
        ('ordenes_de_trabajo', '0015_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa legal (RUC) bajo la cual factura esta sucursal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='empresa.empresaemisora'),
        ),
    ]
