# Generated by Django 6.0 on 2026-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0016_sucursal_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero_orden',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
