# Generated by Django 6.0 on 2026-04-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_producto_origen_alter_codigoproducto_codigo_barras_and_more'),
        ('ordenes_de_trabajo', '0017_alter_ordentrabajo_numero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeninsumodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordeninsumodetalle',
            name='descripcion_factura',
            field=models.CharField(blank=True, help_text='Lo que aparecerá impreso en la factura. Se auto-llena con el nombre del producto si se deja en blanco.', max_length=255, verbose_name='Descripción para el Cliente'),
        ),
        migrations.AlterField(
            model_name='ordeninsumodetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.codigoproducto'),
        ),
    ]
