# Generated by Django 6.0.3 on 2026-05-04 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0018_alter_ordeninsumodetalle_cantidad_and_more'),
        ('servicios', '0003_alter_precioservicio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenserviciodetalle',
            name='descripcion_servicio',
            field=models.CharField(help_text='Descripción real que aparece en la OT. Aísla la orden del catálogo núcleo.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordenserviciodetalle',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_detalle', to='servicios.serviciocatalogo'),
        ),
    ]
