# Generated by Django 6.0.3 on 2026-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0019_alter_ordenserviciodetalle_descripcion_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='tipo_servicio',
            field=models.CharField(choices=[('MEC', 'Mano de Obra Interna'), ('EXT', 'Mano de Obra Externa')], default='MEC', max_length=10),
        ),
    ]
