# Generated by Django 6.0 on 2026-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0020_ordenserviciodetalle_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Familiar/Alternativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo/Trabajo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Principal'),
        ),
    ]
