# Generated by Django 6.0.3 on 2026-05-07 09:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0021_cliente_telefono_secundario_cliente_telefono_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeninsumodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordeninsumodetalle',
            name='descripcion_factura',
            field=models.CharField(blank=True, help_text='Lo que aparecerá impreso en la factura.', max_length=255, verbose_name='Descripción para el Cliente'),
        ),
    ]
