# Generated by Django 6.0.3 on 2026-05-07 09:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0022_alter_ordeninsumodetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenserviciodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
    ]
