# Generated by Django 6.0.3 on 2026-05-07 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_codigoproducto_codigo_barras_and_more'),
        ('ordenes_de_trabajo', '0023_alter_ordenserviciodetalle_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='categoria_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='codigo_barras_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='codigo_empaque_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de empaque referencial'),
        ),
    ]
