# Generated by Django 6.0.3 on 2026-05-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0024_ordeninsumodetalle_categoria_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='gama_vehiculo',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('ECONOMICA', 'Económica'), ('MEDIA', 'Media'), ('MEDIA_ALTA', 'Media alta'), ('ALTA', 'Alta'), ('PREMIUM', 'Premium'), ('LUJO', 'Lujo'), ('COMERCIAL', 'Comercial'), ('DEPORTIVA', 'Deportiva')], default='NO_APLICA', max_length=20),
        ),
    ]
