# Generated by Django 6.0.3 on 2026-05-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0025_ordentrabajo_gama_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenserviciodetalle',
            name='tipo_tarifa_aplicada',
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='tipo_tarifa_vehiculo',
            field=models.CharField(default='NO_APLICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='gama_vehiculo',
            field=models.CharField(default='NO_APLICA', max_length=20),
        ),
    ]
