# Generated by Django 6.0.3 on 2026-05-08 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0026_remove_ordenserviciodetalle_tipo_tarifa_aplicada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenserviciodetalle',
            old_name='tipo_tarifa_vehiculo',
            new_name='tipo_tarifa_aplicada',
        ),
        migrations.CreateModel(
            name='OrdenServicioProcedimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_detalle', to='ordenes_de_trabajo.ordenserviciodetalle')),
            ],
            options={
                'verbose_name': 'Procedimiento aplicado en OT',
                'verbose_name_plural': 'Procedimientos aplicados en OT',
                'ordering': ['orden_item', 'id'],
            },
        ),
    ]
