# Generated by Django 6.0.3 on 2026-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0027_rename_tipo_tarifa_vehiculo_ordenserviciodetalle_tipo_tarifa_aplicada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenserviciohistorico',
            name='procedimientos',
            field=models.JSONField(blank=True, default=list, help_text='Sub-procedimientos o líneas hijas del servicio histórico.'),
        ),
    ]
