# Generated by Django 6.0.3 on 2026-05-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0028_ordenserviciohistorico_procedimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
