# Generated by Django 6.0.3 on 2026-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0029_alter_sucursal_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Familiar/Alternativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Fijo/Trabajo'),
        ),
    ]
