# Generated by Django 6.0.3 on 2026-05-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0030_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cédula/RUC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('C', 'Cédula'), ('R', 'RUC'), ('P', 'Pasaporte'), ('S', 'Sin Documento')], default='C', max_length=1),
        ),
    ]
