# Generated by Django 6.0.3 on 2026-05-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0031_alter_cliente_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('C', 'Cédula'), ('R', 'RUC'), ('P', 'Pasaporte'), ('S', 'Sin Documento')], default='S', max_length=1),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['identificacion'], name='ordenes_de__identif_faedc7_idx'),
        ),
    ]
