# Generated by Django 6.0.3 on 2026-05-13 21:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_componentekit_cantidad_and_more'),
        ('ordenes_de_trabajo', '0032_alter_cliente_identificacion_and_more'),
        ('servicios', '0004_servicioprocedimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, unique=True)),
                ('cliente_respaldo', models.CharField(blank=True, max_length=200, null=True)),
                ('placa', models.CharField(db_index=True, max_length=15)),
                ('vehiculo', models.CharField(blank=True, max_length=150, null=True)),
                ('anio_vehiculo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente / Entregada'), ('APROBADA', 'Aprobada (Trasladada a OT)'), ('RECHAZADA', 'Rechazada / Caducada')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('validez_dias', models.PositiveIntegerField(default=15, help_text='Días de validez de los precios')),
                ('total_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Notas para el cliente en la proforma', null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='ordenes_de_trabajo.cliente')),
                ('orden', models.ForeignKey(blank=True, help_text='Si la proforma nace de una OT abierta (Ampliación de presupuesto).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_vinculadas', to='ordenes_de_trabajo.ordentrabajo')),
                ('orden_generada', models.OneToOneField(blank=True, help_text='La OT oficial que nació de esta cotización de mostrador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ordenes_de_trabajo.ordentrabajo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ordenes_de_trabajo.sucursal')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionInsumoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_factura', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_cotizados', to='ordenes_de_trabajo.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.codigoproducto')),
            ],
            options={
                'ordering': ['orden_item', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('MEC', 'Mano de Obra Interna'), ('EXT', 'Mano de Obra Externa')], default='MEC', max_length=10)),
                ('descripcion_servicio', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cotizados', to='ordenes_de_trabajo.cotizacion')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.serviciocatalogo')),
            ],
            options={
                'ordering': ['orden_item', 'id'],
            },
        ),
    ]
