# Generated by Django 6.0.3 on 2026-05-13 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0033_cotizacion_cotizacioninsumodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionProcedimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('servicio_cotizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_detalle', to='ordenes_de_trabajo.cotizacionserviciodetalle')),
            ],
        ),
    ]
