# Generated by Django 6.0.3 on 2026-05-14 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_componentekit_cantidad_and_more'),
        ('ordenes_de_trabajo', '0034_cotizacionprocedimientodetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionprocedimientodetalle',
            options={'ordering': ['orden_item', 'id']},
        ),
        migrations.AddField(
            model_name='cotizacioninsumodetalle',
            name='categoria_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='cotizacioninsumodetalle',
            name='codigo_barras_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacioninsumodetalle',
            name='codigo_empaque_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionprocedimientodetalle',
            name='orden_item',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
