# Generated by Django 6.0.3 on 2026-05-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0035_alter_cotizacionprocedimientodetalle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='orden',
            field=models.OneToOneField(blank=True, help_text='Si la proforma nace de una OT abierta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_vinculada', to='ordenes_de_trabajo.ordentrabajo'),
        ),
    ]
