# Generated by Django 6.0.3 on 2026-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0037_cliente_actividad_economica_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='canton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='carnet_conadis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contribuyente_fantasma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='datos_full_consultados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='discapacidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultima_consulta_api',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='licencia_todos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cliente',
            name='otras_direcciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cliente',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='porcentaje_discapacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='transacciones_inexistentes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='instruccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Familiar/Alternativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Trabajo/Fijo'),
        ),
    ]
