# Generated by Django 6.0.3 on 2026-05-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0038_cliente_canton_cliente_carnet_conadis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientevehiculo',
            name='datos_api_placa',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='descripcion_api',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='fecha_ultima_consulta_placa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='imagen_url_api',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='marca_api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='modelo_api',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='numero_chasis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de chasis / VIN'),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='subtipo_vehiculo_api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expedientevehiculo',
            name='tipo_vehiculo_api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='expedientevehiculo',
            index=models.Index(fields=['marca_api'], name='ordenes_de__marca_a_c62298_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientevehiculo',
            index=models.Index(fields=['modelo_api'], name='ordenes_de__modelo__4c37ac_idx'),
        ),
    ]
