# Generated by Django 6.0.3 on 2026-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0039_expedientevehiculo_datos_api_placa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientevehiculo',
            name='clave_encendido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave/PIN de Encendido'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='clave_encendido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave/PIN de Encendido'),
        ),
    ]
