# Generated by Django 6.0.3 on 2026-05-20 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0040_expedientevehiculo_clave_encendido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=150)),
                ('texto', models.TextField()),
                ('tipo_documento', models.CharField(choices=[('AMBOS', 'Cotización y orden'), ('COTIZACION', 'Solo cotización'), ('ORDEN', 'Solo orden de trabajo')], db_index=True, default='AMBOS', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['orden_visual', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='OrdenObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_items', to='ordenes_de_trabajo.ordentrabajo')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes_de_trabajo.plantillaobservacion')),
            ],
            options={
                'ordering': ['orden_item', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_items', to='ordenes_de_trabajo.cotizacion')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes_de_trabajo.plantillaobservacion')),
            ],
            options={
                'ordering': ['orden_item', 'id'],
            },
        ),
    ]
