# Generated by Django 6.0.3 on 2026-05-20 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0041_plantillaobservacion_ordenobservacion_and_more'),
        ('servicios', '0005_serviciocatalogo_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenobservacion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordenobservacion',
            name='plantilla',
        ),
        migrations.CreateModel(
            name='PlantillaRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=150)),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
                ('servicios', models.ManyToManyField(blank=True, related_name='recomendaciones_sugeridas', to='servicios.serviciocatalogo')),
            ],
            options={
                'ordering': ['orden_visual', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='OrdenRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_items', to='ordenes_de_trabajo.ordentrabajo')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes_de_trabajo.plantillarecomendacion')),
            ],
            options={
                'verbose_name': 'Recomendación de orden',
                'verbose_name_plural': 'Recomendaciones de órdenes',
                'ordering': ['orden_item', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='CotizacionObservacion',
        ),
        migrations.DeleteModel(
            name='OrdenObservacion',
        ),
        migrations.DeleteModel(
            name='PlantillaObservacion',
        ),
    ]
