# Generated by Django 6.0.3 on 2026-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0042_remove_ordenobservacion_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione uno o varios técnicos que trabajarán en esta orden.', related_name='ordenes_asignadas', to='ordenes_de_trabajo.tecnico', verbose_name='Técnicos encargados'),
        ),
    ]
