# Generated by Django 6.0.3 on 2026-05-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0043_ordentrabajo_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cédula / Identificación'),
        ),
    ]
