# Generated by Django 6.0.3 on 2026-06-05 04:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_remove_empresaemisora_porcentaje_iva_and_more'),
        ('ordenes_de_trabajo', '0044_tecnico_cedula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='porcentaje_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='subtotal_sin_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_vinculada', to='ordenes_de_trabajo.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='orden_generada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ordenes_de_trabajo.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='validez_dias',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='ordencroquisdanio',
            name='trazos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ordeninsumodetalle',
            name='descripcion_factura',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción para el Cliente'),
        ),
        migrations.AlterField(
            model_name='ordenserviciodetalle',
            name='descripcion_servicio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordenserviciohistorico',
            name='procedimientos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='firma_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='ordenes/firmas/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='hash_migracion',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='ordenes_asignadas', to='ordenes_de_trabajo.tecnico', verbose_name='Técnicos encargados'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='empresa.empresaemisora'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='configuracion_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='ordenes_de_trabajo.configuraciontributaria'),
        ),
    ]
