# Generated by Django 6.0.3 on 2026-07-07 03:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0046_ordeninsumodetalle_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacioninsumodetalle',
            options={'ordering': ['orden_item', 'id'], 'verbose_name': 'Repuesto cotizado', 'verbose_name_plural': 'Repuestos cotizados'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionprocedimientodetalle',
            options={'ordering': ['orden_item', 'id'], 'verbose_name': 'Procedimiento cotizado', 'verbose_name_plural': 'Procedimientos cotizados'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionserviciodetalle',
            options={'ordering': ['orden_item', 'id'], 'verbose_name': 'Servicio cotizado', 'verbose_name_plural': 'Servicios cotizados'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='configuracion_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ordenes_de_trabajo.configuraciontributaria'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='gama_vehiculo',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('ECONOMICA', 'Económica'), ('MEDIA', 'Media'), ('MEDIA_ALTA', 'Media alta'), ('ALTA', 'Alta'), ('PREMIUM', 'Premium'), ('LUJO', 'Lujo'), ('COMERCIAL', 'Comercial'), ('DEPORTIVA', 'Deportiva')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_sin_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_tarifa_vehiculo',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('AUTO', 'Auto'), ('AUTO_3P', 'Auto 3 puertas'), ('AUTO_5P', 'Auto 5 puertas'), ('SUV_3P', 'SUV 3 puertas'), ('SUV_5P', 'SUV 5 puertas'), ('CAMIONETA_CS', 'Camioneta cabina sencilla'), ('CAMIONETA_DC', 'Camioneta doble cabina'), ('CAMIONETA_GRANDE', 'Camioneta grande')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacionserviciodetalle',
            name='tipo_tarifa_aplicada',
            field=models.CharField(default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacionserviciodetalle',
            name='variante_precio_aplicada',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('REPINTADO', 'Repintado'), ('NUEVO', 'Nuevo'), ('TRICAPA', 'Tricapa / Candys'), ('ESPECIAL', 'Color especial')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacioninsumodetalle',
            name='descripcion_factura',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción para el Cliente'),
        ),
    ]
