# Generated by Django 6.0.3 on 2026-07-25 02:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0047_alter_cotizacioninsumodetalle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='descuento_ingresado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor escrito por el usuario, como porcentaje o valor fijo.', max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sumar_iva_al_total',
            field=models.BooleanField(default=True, help_text='El IVA siempre se calcula y se muestra. Este campo define si se suma al total final.', verbose_name='Sumar IVA al total'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_descuento',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('VALOR_FIJO', 'Valor fijo ($)')], default='PORCENTAJE', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Porcentaje real o equivalente calculado por el sistema.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Valor monetario del descuento calculado por el sistema.', max_digits=12),
        ),
    ]
