# Generated by Django 6.0.3 on 2026-07-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0048_ordentrabajo_descuento_ingresado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='intervalo_mantenimiento_km',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de kilómetros que se sumará al kilometraje actual para calcular el próximo mantenimiento.', null=True, verbose_name='Intervalo de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje actual'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='proximo_mantenimiento_km',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Próximo mantenimiento'),
        ),
    ]
