# Generated by Django 6.0.3 on 2026-08-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0049_ordentrabajo_intervalo_mantenimiento_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='marcado',
            field=models.BooleanField(default=False, verbose_name='Marcado visual'),
        ),
    ]
