# Generated by Django 6.0.3 on 2026-08-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0050_ordeninsumodetalle_marcado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'En Taller / Abierta'), ('CERRADA', 'Trabajo completado / Lista para facturar'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=15),
        ),
    ]
