# Generated by Django 6.0.3 on 2026-08-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0050_ordeninsumodetalle_marcado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='gama_vehiculo',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='tipo_tarifa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='cotizacionserviciodetalle',
            name='tipo_tarifa_aplicada',
        ),
        migrations.RemoveField(
            model_name='ordenserviciodetalle',
            name='tipo_tarifa_aplicada',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='gama_vehiculo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tipo_tarifa_vehiculo',
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'En Taller / Abierta'), ('CERRADA', 'Trabajo completado / Lista para facturar'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=15),
        ),
    ]
