# Generated by Django 6.0.3 on 2026-09-09 03:48

from django.db import migrations, models


def configurar_corte_facturacion_mao(
    apps,
    schema_editor,
):
    """
    Configura el corte inicial de facturación.

    Reglas:

    1. Todas las OT que ya existían quedan inicialmente
       NO facturables en MAO.

    2. Las OT que actualmente están ABIERTAS quedan
       habilitadas para ser facturadas en MAO cuando
       posteriormente sean cerradas.

    3. Las OT que ya tienen una FacturaVenta creada
       dentro de MAO también se consideran pertenecientes
       al período MAO.

    4. Las OT nuevas creadas después de esta migración
       tendrán facturable_en_mao=True gracias al default
       definido en el modelo.
    """

    OrdenTrabajo = apps.get_model(
        "ordenes_de_trabajo",
        "OrdenTrabajo",
    )

    FacturaVenta = apps.get_model(
        "facturacion",
        "FacturaVenta",
    )

    db_alias = schema_editor.connection.alias

    # =====================================================
    # 1. BLOQUEAR TODAS LAS OT EXISTENTES
    # =====================================================

    (
        OrdenTrabajo.objects
        .using(db_alias)
        .all()
        .update(
            facturable_en_mao=False
        )
    )

    # =====================================================
    # 2. HABILITAR LAS OT QUE ESTÁN ABIERTAS
    # =====================================================

    (
        OrdenTrabajo.objects
        .using(db_alias)
        .filter(
            estado="ABIERTA",
        )
        .update(
            facturable_en_mao=True
        )
    )

    # =====================================================
    # 3. HABILITAR LAS OT YA FACTURADAS DENTRO DE MAO
    # =====================================================

    ids_ordenes_facturadas_mao = (
        FacturaVenta.objects
        .using(db_alias)
        .exclude(
            orden_id__isnull=True,
        )
        .values_list(
            "orden_id",
            flat=True,
        )
    )

    (
        OrdenTrabajo.objects
        .using(db_alias)
        .filter(
            pk__in=ids_ordenes_facturadas_mao,
        )
        .update(
            facturable_en_mao=True
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "ordenes_de_trabajo",
            "0051_remove_cotizacion_gama_vehiculo_and_more",
        ),
        (
            "facturacion",
            "0009_alter_facturaventa_ambiente",
        ),
    ]

    operations = [

        # =================================================
        # NUEVO CAMPO
        # =================================================

        migrations.AddField(
            model_name="ordentrabajo",
            name="facturable_en_mao",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Indica si esta orden pertenece al período "
                    "habilitado para facturación electrónica en MAO."
                ),
            ),
        ),

        # =================================================
        # CORTE INICIAL DE FACTURACIÓN
        # =================================================

        migrations.RunPython(
            configurar_corte_facturacion_mao,
            reverse_code=migrations.RunPython.noop,
        ),
    ]