# Generated by Django 6.0.3 on 2026-09-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0052_ordentrabajo_facturable_en_mao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='facturable_en_mao',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si esta orden pertenece al período habilitado para facturación electrónica en MAO.'),
        ),
    ]
