# Generated by Django 6.0.3 on 2026-09-10 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0053_alter_ordentrabajo_facturable_en_mao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('FACTURADO', 'Facturado'), ('ANULADO', 'Anulado')], db_index=True, default='REGISTRADO', max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='ordenes_de_trabajo.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_orden_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono de orden de trabajo',
                'verbose_name_plural': 'Abonos de órdenes de trabajo',
                'ordering': ['fecha', 'id'],
                'indexes': [models.Index(fields=['orden', 'estado'], name='ordenes_de__orden_i_2baa78_idx'), models.Index(fields=['fecha'], name='ordenes_de__fecha_e9938a_idx')],
            },
        ),
    ]
