# Generated by Django 6.0.3 on 2026-09-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0054_abonoordentrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencroquisdanio',
            name='version_croquis',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
