# Generated by Django 6.0.3 on 2026-09-13 15:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_atributo_tipo_dato_opcioncategoriaatributo'),
        ('ordenes_de_trabajo', '0055_ordencroquisdanio_version_croquis'),
        ('servicios', '0006_alter_precioservicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion', '-revision'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cotizacion_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_siguientes', to='ordenes_de_trabajo.cotizacion'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_ingresado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor escrito por el usuario, como porcentaje o valor fijo.', max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='es_vigente',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sumar_iva_al_total',
            field=models.BooleanField(default=True, help_text='El IVA siempre se calcula y se muestra. Este campo define si se suma al total final.', verbose_name='Sumar IVA al total'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_descuento',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('VALOR_FIJO', 'Valor fijo ($)')], default='PORCENTAJE', max_length=15),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cotizacioninsumodetalle',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacioninsumodetalle',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cotizacioninsumodetalle',
            name='linea_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cotizacioninsumodetalle',
            name='marcado',
            field=models.BooleanField(default=False, verbose_name='Marcado visual'),
        ),
        migrations.AddField(
            model_name='cotizacionprocedimientodetalle',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacionprocedimientodetalle',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cotizacionprocedimientodetalle',
            name='linea_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionserviciodetalle',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacionserviciodetalle',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cotizacionserviciodetalle',
            name='linea_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='cotizacion_linea_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordeninsumodetalle',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos_ot_generados', to='ordenes_de_trabajo.cotizacion'),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='cotizacion_linea_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordenserviciodetalle',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_ot_generados', to='ordenes_de_trabajo.cotizacion'),
        ),
        migrations.AddField(
            model_name='ordenservicioprocedimientodetalle',
            name='cotizacion_linea_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordenservicioprocedimientodetalle',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos_ot_generados', to='ordenes_de_trabajo.cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Porcentaje real o equivalente calculado por el sistema.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente / Entregada'), ('APROBADA', 'Aprobada / Sincronizada con OT'), ('RECHAZADA', 'Rechazada / Caducada')], db_index=True, default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_vinculadas', to='ordenes_de_trabajo.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='orden_generada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_generadas', to='ordenes_de_trabajo.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_cotizacion', 'revision'], name='ordenes_de__numero__9aa416_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['sucursal', 'estado'], name='ordenes_de__sucursa_d7382c_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['placa', 'fecha_creacion'], name='ordenes_de__placa_9d9905_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_cotizacion', 'es_vigente'], name='ordenes_de__numero__487d45_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('numero_cotizacion', 'revision'), name='uq_cotizacion_numero_revision'),
        ),
        migrations.AddConstraint(
            model_name='cotizacioninsumodetalle',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'linea_uuid'), name='uq_cot_insumo_linea'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionprocedimientodetalle',
            constraint=models.UniqueConstraint(fields=('servicio_cotizado', 'linea_uuid'), name='uq_cot_proc_linea'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionserviciodetalle',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'linea_uuid'), name='uq_cot_servicio_linea'),
        ),
    ]
