# Generated by Django 6.0.3 on 2026-09-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0056_alter_cotizacion_options_cotizacion_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_respaldo',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de respaldo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='email_respaldo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de respaldo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='identificacion_cliente_respaldo',
            field=models.CharField(blank=True, help_text='Identificación del cliente congelada al momento de crear la cotización/revisión.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje al cotizar'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono_respaldo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono principal de respaldo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono_secundario_respaldo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono alternativo de respaldo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono_trabajo_respaldo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de trabajo de respaldo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente_respaldo',
            field=models.CharField(blank=True, help_text='Nombre del cliente congelado al momento de crear la cotización/revisión.', max_length=200, null=True),
        ),
    ]
