# Generated by Django 6.0.3 on 2026-09-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0057_cotizacion_direccion_respaldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='direccion_respaldo',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección (respaldo histórico)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='email_respaldo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico (respaldo histórico)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='identificacion_cliente_respaldo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificación del cliente (respaldo histórico)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='telefono_respaldo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono principal (respaldo histórico)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='telefono_secundario_respaldo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono secundario (respaldo histórico)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='telefono_trabajo_respaldo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de trabajo (respaldo histórico)'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente_respaldo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del cliente (respaldo histórico)'),
        ),
    ]
