# Generated by Django 6.0 on 2026-04-18 20:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MEC', 'Mecánica'), ('PIN', 'Pintura'), ('END', 'Enderezada'), ('ELE', 'Electricidad'), ('EXT', 'Trabajo Externo')], max_length=3)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('requiere_tipo_tarifa', models.BooleanField(default=False, help_text='Actívalo si el precio depende del tipo de vehículo.')),
                ('requiere_variante', models.BooleanField(default=False, help_text='Actívalo si el precio depende de variante (repintado, nuevo, tricapa, especial, etc.).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarifa_vehiculo', models.CharField(choices=[('NO_APLICA', 'No aplica'), ('AUTO', 'Auto'), ('AUTO_3P', 'Auto 3 puertas'), ('AUTO_5P', 'Auto 5 puertas'), ('SUV_3P', 'SUV 3 puertas'), ('SUV_5P', 'SUV 5 puertas'), ('CAMIONETA_CS', 'Camioneta cabina sencilla'), ('CAMIONETA_DC', 'Camioneta doble cabina'), ('CAMIONETA_GRANDE', 'Camioneta grande')], default='NO_APLICA', max_length=20)),
                ('variante_precio', models.CharField(choices=[('NORMAL', 'Normal'), ('REPINTADO', 'Repintado'), ('NUEVO', 'Nuevo'), ('TRICAPA', 'Tricapa / Candys'), ('ESPECIAL', 'Color especial')], default='NORMAL', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_configurados', to='servicios.serviciocatalogo')),
            ],
            options={
                'verbose_name': 'Precio de servicio',
                'verbose_name_plural': 'Precios de servicios',
                'ordering': ['servicio__descripcion', 'tipo_tarifa_vehiculo', 'variante_precio'],
                'constraints': [models.UniqueConstraint(fields=('servicio', 'tipo_tarifa_vehiculo', 'variante_precio'), name='uq_precio_servicio_tarifa_variante')],
            },
        ),
    ]
