# Generated by Django 6.0.3 on 2026-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocatalogo',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='serviciocatalogo',
            name='categoria',
            field=models.CharField(choices=[('MEC', 'Mecánica'), ('PIN', 'Pintura'), ('END', 'Enderezada'), ('ELE', 'Electricidad'), ('EXT', 'Trabajo Externo')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='serviciocatalogo',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='precioservicio',
            index=models.Index(fields=['servicio', 'tipo_tarifa_vehiculo'], name='servicios_p_servici_401a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='precioservicio',
            index=models.Index(fields=['servicio', 'variante_precio'], name='servicios_p_servici_ecbcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='precioservicio',
            index=models.Index(fields=['tipo_tarifa_vehiculo', 'variante_precio'], name='servicios_p_tipo_ta_84e3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciocatalogo',
            index=models.Index(fields=['categoria', 'activo'], name='servicios_s_categor_baa46e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciocatalogo',
            index=models.Index(fields=['descripcion'], name='servicios_s_descrip_b29bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciocatalogo',
            index=models.Index(fields=['codigo', 'activo'], name='servicios_s_codigo_193480_idx'),
        ),
    ]
