# Generated by Django 6.0 on 2026-04-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0012_alter_ordentrabajo_sucursal'),
        ('servicios', '0002_alter_serviciocatalogo_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precioservicio',
            options={'ordering': ['sucursal__codigo', 'servicio__descripcion', 'tipo_tarifa_vehiculo', 'variante_precio'], 'verbose_name': 'Precio de servicio', 'verbose_name_plural': 'Precios de servicios'},
        ),
        migrations.RemoveConstraint(
            model_name='precioservicio',
            name='uq_precio_servicio_tarifa_variante',
        ),
        migrations.RemoveIndex(
            model_name='precioservicio',
            name='servicios_p_tipo_ta_84e3f0_idx',
        ),
        migrations.AddField(
            model_name='precioservicio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precios_servicio', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.AddIndex(
            model_name='precioservicio',
            index=models.Index(fields=['sucursal', 'servicio'], name='servicios_p_sucursa_73117b_idx'),
        ),
        migrations.AddIndex(
            model_name='precioservicio',
            index=models.Index(fields=['sucursal', 'tipo_tarifa_vehiculo', 'variante_precio'], name='servicios_p_sucursa_4b5d30_idx'),
        ),
        migrations.AddConstraint(
            model_name='precioservicio',
            constraint=models.UniqueConstraint(fields=('servicio', 'sucursal', 'tipo_tarifa_vehiculo', 'variante_precio'), name='uq_precio_servicio_sucursal_tarifa_variante'),
        ),
    ]
