# Generated by Django 6.0.3 on 2026-05-08 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_precioservicio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Tarea interna incluida dentro del servicio.', max_length=300)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('obligatorio', models.BooleanField(default=True, help_text='Indica si esta tarea siempre debe hacerse dentro del servicio.')),
                ('visible_en_ot', models.BooleanField(default=True, help_text='Permite mostrar esta tarea como checklist interno en la OT.')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='servicios.serviciocatalogo')),
            ],
            options={
                'verbose_name': 'Procedimiento de servicio',
                'verbose_name_plural': 'Procedimientos de servicios',
                'ordering': ['servicio', 'orden', 'id'],
            },
        ),
    ]
