# Generated by Django 6.0.3 on 2026-05-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_servicioprocedimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocatalogo',
            name='tipo_servicio',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('PAQUETE', 'Paquete con procedimientos'), ('VARIABLE', 'Precio variable')], db_index=True, default='SIMPLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciocatalogo',
            name='requiere_tipo_tarifa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciocatalogo',
            name='requiere_variante',
            field=models.BooleanField(default=False),
        ),
    ]
