# Generated by Django 6.0.3 on 2026-08-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_de_trabajo', '0051_remove_cotizacion_gama_vehiculo_and_more'),
        ('servicios', '0005_serviciocatalogo_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precioservicio',
            options={'ordering': ['sucursal__codigo', 'servicio__descripcion', 'variante_precio'], 'verbose_name': 'Precio de servicio', 'verbose_name_plural': 'Precios de servicios'},
        ),
        migrations.RemoveConstraint(
            model_name='precioservicio',
            name='uq_precio_servicio_sucursal_tarifa_variante',
        ),
        migrations.RemoveIndex(
            model_name='precioservicio',
            name='servicios_p_servici_401a9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='precioservicio',
            name='servicios_p_sucursa_4b5d30_idx',
        ),
        migrations.RemoveField(
            model_name='serviciocatalogo',
            name='requiere_tipo_tarifa',
        ),
        migrations.AddIndex(
            model_name='precioservicio',
            index=models.Index(fields=['sucursal', 'variante_precio'], name='servicios_p_sucursa_6dca86_idx'),
        ),
        migrations.AddConstraint(
            model_name='precioservicio',
            constraint=models.UniqueConstraint(fields=('servicio', 'sucursal', 'variante_precio'), name='uq_precio_servicio_sucursal_variante'),
        ),
        migrations.RemoveField(
            model_name='precioservicio',
            name='tipo_tarifa_vehiculo',
        ),
    ]
