# Generated by Django 6.0.3 on 2026-04-17 05:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('ordenes_de_trabajo', '0005_trabajorecepcioncatalogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia_remision', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura')], default='01', editable=False, max_length=2)),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1)),
                ('tipo_emision', models.CharField(choices=[('1', 'Normal')], default='1', max_length=1)),
                ('establecimiento', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')])),
                ('punto_emision', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')])),
                ('secuencial', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 9 dígitos.', regex='^\\d{9}$')])),
                ('clave_acceso', models.CharField(blank=True, editable=False, max_length=49, unique=True)),
                ('codigo_numerico', models.CharField(blank=True, editable=False, max_length=8)),
                ('tipo_identificacion_comprador', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final')], default='05', max_length=2)),
                ('razon_social_comprador', models.CharField(max_length=300)),
                ('identificacion_comprador', models.CharField(max_length=20)),
                ('direccion_comprador', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono_comprador', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_comprador', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_iva_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_iva_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('propina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('importe_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('moneda', models.CharField(choices=[('DOLAR', 'Dólar')], default='DOLAR', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'XML Generado'), ('FIRMADO', 'XML Firmado'), ('RECIBIDO', 'Recibido por SRI'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado/Error')], default='BORRADOR', max_length=15)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('mensaje_sri', models.TextField(blank=True, null=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('huella_firma', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje_firma', models.TextField(blank=True, null=True)),
                ('xml_generado', models.FileField(blank=True, null=True, upload_to='facturas/ventas/xml/generado/')),
                ('xml_firmado', models.FileField(blank=True, null=True, upload_to='facturas/ventas/xml/firmado/')),
                ('xml_autorizado', models.FileField(blank=True, null=True, upload_to='facturas/ventas/xml/autorizado/')),
                ('pdf_ride', models.FileField(blank=True, null=True, upload_to='facturas/ventas/pdf/')),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='empresa.empresaemisora')),
                ('firma_electronica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='empresa.firmaelectronica')),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_electronica', to='ordenes_de_trabajo.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Factura de venta',
                'verbose_name_plural': 'Facturas de venta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_principal', models.CharField(max_length=50)),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('codigo_impuesto', models.CharField(default='2', help_text='2 = IVA', max_length=1)),
                ('codigo_porcentaje_iva', models.CharField(choices=[('0', '0%'), ('4', '15%')], default='4', max_length=1)),
                ('tarifa_iva', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.facturaventa')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PagoFacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos')], max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo', models.PositiveIntegerField(default=0)),
                ('unidad_tiempo', models.CharField(default='Días', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.facturaventa')),
            ],
            options={
                'verbose_name': 'Pago de factura',
                'verbose_name_plural': 'Pagos de factura',
            },
        ),
        migrations.AddConstraint(
            model_name='facturaventa',
            constraint=models.UniqueConstraint(fields=('empresa', 'establecimiento', 'punto_emision', 'secuencial'), name='unique_factura_serie_secuencial'),
        ),
    ]
