# Generated by Django 6.0 on 2026-04-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_firmaelectronica_options_and_more'),
        ('facturacion', '0001_initial'),
        ('ordenes_de_trabajo', '0012_alter_ordentrabajo_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_venta', to='ordenes_de_trabajo.sucursal'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['sucursal', 'fecha_emision'], name='facturacion_sucursa_ceb1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'fecha_emision'], name='facturacion_empresa_e92bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['estado'], name='facturacion_estado_7bfc59_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['clave_acceso'], name='facturacion_clave_a_54f56d_idx'),
        ),
    ]
