# Generated by Django 6.0.3 on 2026-06-05 04:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_facturaventa_sucursal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaventa',
            old_name='iva_15',
            new_name='valor_iva',
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='subtotal_iva_15',
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='subtotal_gravado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallefacturaventa',
            name='codigo_porcentaje_iva',
            field=models.CharField(choices=[('0', '0%'), ('4', 'IVA vigente')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='detallefacturaventa',
            name='tarifa_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
