# Generated by Django 6.0.3 on 2026-06-05 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_rename_iva_15_facturaventa_valor_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
