# Generated by Django 6.0.3 on 2026-08-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_facturaventa_porcentaje_iva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefacturaventa',
            options={'ordering': ['tipo_origen', 'orden_origen', 'id'], 'verbose_name': 'Detalle de factura', 'verbose_name_plural': 'Detalles de factura'},
        ),
        migrations.AddField(
            model_name='detallefacturaventa',
            name='orden_origen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallefacturaventa',
            name='tipo_origen',
            field=models.CharField(choices=[('REP', 'Repuesto'), ('MOI', 'Mano de Obra Interna'), ('MOE', 'Mano de Obra Externa'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=10),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='anio_vehiculo_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='color_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='kilometraje_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='numero_orden_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='placa_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='vehiculo_snapshot',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='ProcedimientoDetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='facturacion.detallefacturaventa')),
            ],
            options={
                'verbose_name': 'Procedimiento de detalle de factura',
                'verbose_name_plural': 'Procedimientos de detalles de factura',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
