# Generated by Django 6.0.3 on 2026-08-29 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_detallefacturaventa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagofacturaventa',
            options={'ordering': ['id'], 'verbose_name': 'Pago de factura', 'verbose_name_plural': 'Pagos de factura'},
        ),
        migrations.AddField(
            model_name='pagofacturaventa',
            name='entidad_financiera_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pagofacturaventa',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pagofacturaventa',
            name='referencia',
            field=models.CharField(blank=True, default='', help_text='Número de transferencia, voucher, autorización u otra referencia.', max_length=100),
        ),
        migrations.CreateModel(
            name='EntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('COOPERATIVA', 'Cooperativa'), ('MUTUALISTA', 'Mutualista'), ('OTRA', 'Otra')], db_index=True, default='BANCO', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entidad financiera',
                'verbose_name_plural': 'Entidades financieras',
                'ordering': ['orden', 'tipo', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'tipo'], name='facturacion_activo_fbcfc9_idx'), models.Index(fields=['orden', 'nombre'], name='facturacion_orden_595a8b_idx')],
            },
        ),
        migrations.AddField(
            model_name='pagofacturaventa',
            name='entidad_financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='facturacion.entidadfinanciera'),
        ),
        migrations.AddIndex(
            model_name='pagofacturaventa',
            index=models.Index(fields=['factura', 'forma_pago'], name='facturacion_factura_1e25c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagofacturaventa',
            index=models.Index(fields=['entidad_financiera'], name='facturacion_entidad_e154aa_idx'),
        ),
    ]
