# Generated by Django 6.0.3 on 2026-08-31 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_pagofacturaventa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturaventa',
            name='tipo_origen',
            field=models.CharField(choices=[('REP', 'Repuesto'), ('MOI', 'Mano de Obra Interna'), ('MOE', 'Mano de Obra Externa'), ('MANUAL', 'Venta manual')], db_index=True, default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='clave_acceso',
            field=models.CharField(blank=True, editable=False, max_length=49, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='secuencial',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 9 dígitos.', regex='^\\d{9}$')]),
        ),
    ]
