# Generated by Django 6.0.3 on 2026-09-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_remove_empresaemisora_porcentaje_iva_and_more'),
        ('facturacion', '0007_alter_detallefacturaventa_tipo_origen_and_more'),
        ('ordenes_de_trabajo', '0051_remove_cotizacion_gama_vehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facturaventa',
            name='unique_factura_serie_secuencial',
        ),
        migrations.AddConstraint(
            model_name='facturaventa',
            constraint=models.UniqueConstraint(fields=('empresa', 'ambiente', 'establecimiento', 'punto_emision', 'secuencial'), name='unique_factura_ambiente_serie_secuencial'),
        ),
    ]
