# Generated by Django 6.0.3 on 2026-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_remove_facturaventa_unique_factura_serie_secuencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='ambiente',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='2', max_length=1),
        ),
    ]
