# Generated by Django 6.0.3 on 2026-09-10 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_facturaventa_ambiente'),
        ('ordenes_de_trabajo', '0054_abonoordentrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='abono_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ordenes_de_trabajo.abonoordentrabajo'),
        ),
        migrations.AlterField(
            model_name='detallefacturaventa',
            name='tipo_origen',
            field=models.CharField(choices=[('REP', 'Repuesto'), ('MOI', 'Mano de Obra Interna'), ('MOE', 'Mano de Obra Externa'), ('ANTICIPO', 'Anticipo de OT'), ('MANUAL', 'Venta manual')], db_index=True, default='MANUAL', max_length=10),
        ),
    ]
