# Generated by Django 6.0.3 on 2026-09-21 05:05

import asistencia.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_de_trabajo', '0058_ordentrabajo_direccion_respaldo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAsistenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('habilitado', models.BooleanField(default=True, help_text='Indica si este usuario puede utilizar el sistema de asistencia.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_asistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de asistencia',
                'verbose_name_plural': 'Configuraciones de asistencia',
            },
        ),
        migrations.CreateModel(
            name='HorarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('minutos_almuerzo', models.PositiveSmallIntegerField(default=60)),
                ('tolerancia_entrada_minutos', models.PositiveSmallIntegerField(default=0, help_text='Minutos de tolerancia después de la hora de entrada.')),
                ('tolerancia_almuerzo_minutos', models.PositiveSmallIntegerField(default=0, help_text='Minutos adicionales permitidos sobre la duración del almuerzo.')),
                ('tolerancia_salida_minutos', models.PositiveSmallIntegerField(default=0, help_text='Minutos permitidos para salir antes de la hora establecida.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario_asistencia', to='ordenes_de_trabajo.sucursal')),
            ],
            options={
                'verbose_name': 'Horario de sucursal',
                'verbose_name_plural': 'Horarios de sucursales',
                'ordering': ['sucursal__codigo'],
            },
        ),
        migrations.CreateModel(
            name='TerminalAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(db_index=True, help_text='Ejemplo: NORTE-01 o SUR-01.', max_length=50, unique=True)),
                ('token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('activa', models.BooleanField(default=True)),
                ('ultima_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminales_asistencia', to='ordenes_de_trabajo.sucursal')),
            ],
            options={
                'verbose_name': 'Terminal de asistencia',
                'verbose_name_plural': 'Terminales de asistencia',
                'ordering': ['sucursal__codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('INICIO_ALMUERZO', 'Inicio de almuerzo'), ('FIN_ALMUERZO', 'Fin de almuerzo'), ('SALIDA', 'Salida')], db_index=True, max_length=30)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate, editable=False)),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_dispositivo', models.DateTimeField(blank=True, null=True)),
                ('es_offline', models.BooleanField(db_index=True, default=False)),
                ('fotografia', models.ImageField(upload_to=asistencia.models.ruta_foto_asistencia)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_asistencia', to='ordenes_de_trabajo.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='asistencia.terminalasistencia')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-fecha_hora'],
                'permissions': [('ver_todas_sucursales_asistencia', 'Ver asistencia de todas las sucursales'), ('corregir_asistencia', 'Corregir asistencia')],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('ATRASO_ENTRADA', 'Atraso de entrada'), ('EXCESO_ALMUERZO', 'Exceso de almuerzo'), ('SALIDA_ANTICIPADA', 'Salida anticipada'), ('MARCACION_FALTANTE', 'Marcación faltante'), ('JORNADA_INCOMPLETA', 'Jornada incompleta'), ('MARCACION_OFFLINE', 'Marcación offline'), ('TIEMPO_POSTERIOR_JORNADA', 'Tiempo posterior a la jornada'), ('CORRECCION_MANUAL', 'Corrección manual')], db_index=True, max_length=40)),
                ('minutos', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('JUSTIFICADA', 'Justificada'), ('NO_JUSTIFICADA', 'No justificada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('generado_automaticamente', models.BooleanField(default=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asistencia_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_asistencia', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='asistencia.registroasistencia')),
            ],
            options={
                'verbose_name': 'Incidencia de asistencia',
                'verbose_name_plural': 'Incidencias de asistencia',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='asistencia__usuario_1974a7_idx'), models.Index(fields=['estado', 'fecha'], name='asistencia__estado_290a43_idx'), models.Index(fields=['tipo', 'fecha'], name='asistencia__tipo_bbf049_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['usuario', 'fecha'], name='asistencia__usuario_a96567_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['sucursal', 'fecha'], name='asistencia__sucursa_f44461_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['fecha', 'tipo'], name='asistencia__fecha_a8b499_idx'),
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha', 'tipo'), name='asistencia_marcacion_unica_usuario_fecha_tipo'),
        ),
    ]
