# Generated by Django 6.0.3 on 2026-09-21 06:06

import asistencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalasistencia',
            name='requiere_foto',
            field=models.BooleanField(default=False, help_text='Indica si esta terminal exige una fotografía para registrar la asistencia.'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=asistencia.models.ruta_foto_asistencia),
        ),
    ]
