# Generated by Django 6.0.3 on 2026-09-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_terminalasistencia_requiere_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalasistencia',
            name='requiere_foto',
        ),
    ]
