# Generated by Django 6.0.3 on 2026-09-21 06:50

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_terminalasistencia_requiere_foto'),
        ('ordenes_de_trabajo', '0058_ordentrabajo_direccion_respaldo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='uuid_marcacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['terminal', 'fecha'], name='asistencia__termina_b2426a_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['es_offline', 'fecha'], name='asistencia__es_offl_83f02e_idx'),
        ),
    ]
