# Generated by Django 6.0.3 on 2026-09-11 04:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_de_trabajo', '0054_abonoordentrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=30, unique=True)),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo_origen', models.CharField(choices=[('MANUAL', 'Manual'), ('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('COBRO', 'Cobro'), ('PAGO', 'Pago'), ('INVENTARIO', 'Inventario'), ('AJUSTE', 'Ajuste')], default='MANUAL', max_length=20)),
                ('origen_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='ordenes_de_trabajo.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto'), ('ORDEN', 'Cuenta de orden')], max_length=20)),
                ('permite_movimiento', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuentacontable')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'mes'), name='contabilidad_periodo_unico'), models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='contabilidad_mes_valido')],
            },
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.periodocontable'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['tipo_origen', 'origen_id'], name='contabilida_tipo_or_ddd066_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha', 'estado'], name='contabilida_fecha_31d028_idx'),
        ),
    ]
