# Generated by Django 6.0.3 on 2026-04-22 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_facturacompra_remove_facturacompraxml_proveedor_rel_and_more'),
        ('inventario', '0007_alter_usuario_managers'),
        ('ordenes_de_trabajo', '0012_alter_ordentrabajo_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_solicitada', models.CharField(max_length=255)),
                ('codigo_referencia', models.CharField(blank=True, help_text='Código proveedor / empaque / referencia conocida', max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('marca_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('stock_actual_sucursal', models.PositiveIntegerField(default=0)),
                ('requiere_compra', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('orden_item', models.PositiveIntegerField(default=1)),
                ('codigo_producto_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_cotizacion', to='inventario.codigoproducto')),
                ('producto_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_cotizacion', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Ítem de solicitud',
                'verbose_name_plural': 'Ítems de solicitud',
                'ordering': ['orden_item', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cotizaciones/items/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cotizaciones.itemsolicitudcotizacion')),
            ],
            options={
                'verbose_name': 'Foto de ítem a cotizar',
                'verbose_name_plural': 'Fotos de ítems a cotizar',
                'ordering': ['fecha_subida', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Repuestos faltantes OT-00025', max_length=200)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('urgente', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('RESPONDIDA', 'Con respuestas'), ('DECIDIDA', 'Decidida'), ('COMPRADA', 'Comprada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cotizacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cotizacion', to='ordenes_de_trabajo.ordentrabajo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cotizacion', to='ordenes_de_trabajo.sucursal')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='itemsolicitudcotizacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.solicitudcotizacion'),
        ),
        migrations.CreateModel(
            name='DecisionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, help_text='Ej: mejor relación calidad/precio, disponibilidad inmediata, proveedor confiable', null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('decidida_en', models.DateTimeField(auto_now_add=True)),
                ('decidida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_cotizacion_tomadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor_seleccionado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_ganadas', to='compras.proveedor')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_final', to='cotizaciones.solicitudcotizacion')),
            ],
            options={
                'verbose_name': 'Decisión de cotización',
                'verbose_name_plural': 'Decisiones de cotización',
                'ordering': ['-decidida_en'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proveedor', models.CharField(choices=[('MENOR', 'Menor / Repuestero'), ('MAYOR', 'Mayorista')], default='MENOR', max_length=10)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('tiempo_entrega', models.CharField(blank=True, help_text='Ej: inmediato, 1 hora, mañana, 2 días', max_length=100, null=True)),
                ('calidad_referencial', models.PositiveSmallIntegerField(default=3, help_text='Escala 1 a 5')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('whatsapp_destino', models.CharField(blank=True, max_length=30, null=True)),
                ('mensaje_generado', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('RESPONDIO', 'Respondió'), ('DESCARTADA', 'Descartada'), ('GANADORA', 'Ganadora')], default='PENDIENTE', max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_emitidas', to='compras.proveedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_proveedor', to='cotizaciones.itemsolicitudcotizacion')),
            ],
            options={
                'verbose_name': 'Cotización de proveedor',
                'verbose_name_plural': 'Cotizaciones de proveedores',
                'ordering': ['item', 'estado', 'precio', 'id'],
                'indexes': [models.Index(fields=['estado'], name='cotizacione_estado_02aadd_idx'), models.Index(fields=['proveedor', 'estado'], name='cotizacione_proveed_6c2e76_idx'), models.Index(fields=['precio'], name='cotizacione_precio_05ba6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'proveedor'), name='uq_cotizacion_item_proveedor')],
            },
        ),
        migrations.CreateModel(
            name='ProveedorEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proveedor', models.CharField(choices=[('MENOR', 'Menor / Repuestero'), ('MAYOR', 'Mayorista')], default='MENOR', max_length=10)),
                ('categoria', models.CharField(blank=True, help_text='Ej: FILTROS, FRENOS, SUSPENSION, MOTOR', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, help_text='Ej: TOYOTA, CHEVROLET, HYUNDAI, WIX, FRAM', max_length=100, null=True)),
                ('prioridad', models.PositiveIntegerField(default=1, help_text='Menor número = mayor prioridad al sugerir proveedor.')),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades_cotizacion', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Especialidad de proveedor',
                'verbose_name_plural': 'Especialidades de proveedores',
                'ordering': ['prioridad', 'proveedor__empresa', 'proveedor__nombre_contacto'],
                'indexes': [models.Index(fields=['activo', 'tipo_proveedor'], name='cotizacione_activo_d79f4f_idx'), models.Index(fields=['categoria'], name='cotizacione_categor_918cf0_idx'), models.Index(fields=['marca'], name='cotizacione_marca_7f5256_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacion',
            index=models.Index(fields=['estado', 'creada_en'], name='cotizacione_estado_0014ff_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacion',
            index=models.Index(fields=['sucursal', 'estado'], name='cotizacione_sucursa_6a1be4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudcotizacion',
            index=models.Index(fields=['codigo_referencia'], name='cotizacione_codigo__b640fb_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudcotizacion',
            index=models.Index(fields=['codigo_barras'], name='cotizacione_codigo__515795_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudcotizacion',
            index=models.Index(fields=['marca_referencia'], name='cotizacione_marca_r_6f19ce_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudcotizacion',
            index=models.Index(fields=['categoria_referencia'], name='cotizacione_categor_aa01e4_idx'),
        ),
    ]
