# Generated by Django 6.0.3 on 2026-06-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionproveedor',
            name='calidad_referencial',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='cotizacionproveedor',
            name='tiempo_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='decisioncotizacion',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemsolicitudcotizacion',
            name='codigo_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedorespecialidad',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedorespecialidad',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedorespecialidad',
            name='prioridad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
