# Generated by Django 6.0.3 on 2026-04-17 05:22

import django.core.validators
import django.db.models.deletion
import empresa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('resolucion_agente_retencion', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(max_length=300)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, null=True)),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 13 dígitos.', regex='^\\d{13}$')])),
                ('dir_matriz', models.CharField(max_length=500)),
                ('dir_establecimiento', models.CharField(max_length=500)),
                ('establecimiento', models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')])),
                ('punto_emision', models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')])),
                ('contribuyente_especial', models.CharField(blank=True, max_length=20, null=True)),
                ('obligado_contabilidad', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2)),
                ('agente_retencion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa emisora',
                'verbose_name_plural': 'Empresas emisoras',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='FirmaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno para identificar la firma.', max_length=100)),
                ('titular', models.CharField(help_text='Nombre del titular de la firma electrónica.', max_length=200)),
                ('ruc', models.CharField(help_text='RUC asociado a la firma.', max_length=13, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 13 dígitos.', regex='^\\d{13}$')])),
                ('archivo_firma', models.FileField(help_text='Archivo de firma electrónica .p12 o .pfx', upload_to='firmas_electronicas/', validators=[empresa.models.validar_archivo_firma])),
                ('password_firma', models.CharField(help_text='Contraseña de la firma electrónica. Luego conviene cifrar este campo.', max_length=255)),
                ('entidad_certificadora', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='empresa.empresaemisora')),
            ],
            options={
                'verbose_name': 'Firma electrónica',
                'verbose_name_plural': 'Firmas electrónicas',
                'ordering': ['-id'],
            },
        ),
    ]
