# Generated by Django 6.0 on 2026-04-20 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmaelectronica',
            options={'ordering': ['empresa__razon_social', 'nombre', '-id'], 'verbose_name': 'Firma electrónica', 'verbose_name_plural': 'Firmas electrónicas'},
        ),
        migrations.AlterField(
            model_name='empresaemisora',
            name='establecimiento',
            field=models.CharField(default='001', help_text='Valor por defecto para facturación si la sucursal no define uno propio.', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='empresaemisora',
            name='punto_emision',
            field=models.CharField(default='001', help_text='Valor por defecto para facturación si la sucursal no define uno propio.', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')]),
        ),
        migrations.AddIndex(
            model_name='empresaemisora',
            index=models.Index(fields=['ruc'], name='empresa_emp_ruc_3a8ead_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaemisora',
            index=models.Index(fields=['activo'], name='empresa_emp_activo_50e929_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaemisora',
            index=models.Index(fields=['razon_social'], name='empresa_emp_razon_s_4c2d64_idx'),
        ),
        migrations.AddIndex(
            model_name='firmaelectronica',
            index=models.Index(fields=['ruc'], name='empresa_fir_ruc_61d8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='firmaelectronica',
            index=models.Index(fields=['estado'], name='empresa_fir_estado_31fcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='firmaelectronica',
            index=models.Index(fields=['empresa', 'estado'], name='empresa_fir_empresa_8c5527_idx'),
        ),
    ]
