# Generated by Django 6.0.3 on 2026-04-23 23:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_firmaelectronica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaemisora',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje actual del IVA (ej. 15.00 o 12.00)', max_digits=5),
        ),
    ]
