# Generated by Django 6.0.3 on 2026-06-05 04:43

import django.core.validators
import empresa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresaemisora_porcentaje_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaemisora',
            name='porcentaje_iva',
        ),
        migrations.AlterField(
            model_name='empresaemisora',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='empresaemisora',
            name='punto_emision',
            field=models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 3 dígitos.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='firmaelectronica',
            name='archivo_firma',
            field=models.FileField(upload_to='firmas_electronicas/', validators=[empresa.models.validar_archivo_firma]),
        ),
        migrations.AlterField(
            model_name='firmaelectronica',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='firmaelectronica',
            name='password_firma',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='firmaelectronica',
            name='ruc',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 13 dígitos.', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='firmaelectronica',
            name='titular',
            field=models.CharField(max_length=200),
        ),
    ]
