# Generated by Django 6.0.3 on 2026-04-17 05:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompraXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso_sri', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de Acceso SRI')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='facturas/xml/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('imagen_factura', models.ImageField(blank=True, null=True, upload_to='facturas/fotos/%Y/%m/')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Proveedor')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='R.U.C.')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de Factura')),
                ('clave_acceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de Acceso / Autorización')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Factura')),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado (Efectivo/Transf inmediata)'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('dias_plazo', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vence el')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('esta_pagada', models.BooleanField(default=False, verbose_name='¿Pagada?')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carga de Documento (XML/PDF/Foto)',
                'verbose_name_plural': 'Cargas de Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFacturaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sri', models.CharField(max_length=100)),
                ('descripcion_original', models.CharField(max_length=250, verbose_name='Texto Original (Proveedor)')),
                ('nombre_limpio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Normalizado (Sistema)')),
                ('marca_limpia', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_limpia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingresado_al_inventario', models.BooleanField(default=False)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturacompraxml')),
            ],
            options={
                'verbose_name': 'Repuesto en Revisión',
                'verbose_name_plural': 'Repuestos en Revisión',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=100)),
                ('descripcion_proveedor', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_originales', to='compras.facturacompraxml')),
            ],
            options={
                'verbose_name': 'Detalle Original Proveedor',
                'verbose_name_plural': '📄 1. Detalles Originales (Intocables)',
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('comprobante_banco', models.CharField(blank=True, max_length=100)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='compras.facturacompraxml')),
            ],
            options={
                'verbose_name': 'Abono a Proveedor',
                'verbose_name_plural': 'Abonos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
