# Generated by Django 6.0.3 on 2026-04-18 05:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefacturaoriginal',
            options={'ordering': ['id'], 'verbose_name': 'Detalle Original Proveedor', 'verbose_name_plural': '📄 1. Detalles Originales (Intocables)'},
        ),
        migrations.AlterModelOptions(
            name='pagoproveedor',
            options={'ordering': ['-fecha_pago', '-id'], 'verbose_name': 'Abono a Proveedor', 'verbose_name_plural': 'Abonos a Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['empresa', 'nombre_contacto'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='facturacompraxml',
            name='proveedor_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra', to='compras.proveedor', verbose_name='Proveedor relacionado'),
        ),
        migrations.AlterField(
            model_name='facturacompraxml',
            name='dias_plazo',
            field=models.PositiveIntegerField(default=0, help_text='Ej: 15, 30 días'),
        ),
        migrations.AlterField(
            model_name='facturacompraxml',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Factura'),
        ),
        migrations.CreateModel(
            name='DetalleFacturaNormalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_limpio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Normalizado (Sistema)')),
                ('marca_limpia', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_limpia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingresado_al_inventario', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('detalle_original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_normalizado', to='compras.detallefacturaoriginal')),
            ],
            options={
                'verbose_name': 'Repuesto Normalizado',
                'verbose_name_plural': '🛠️ 2. Repuestos Normalizados',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='DetalleFacturaTemporal',
        ),
    ]
