# Generated by Django 6.0 on 2026-04-20 21:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_detallefacturaoriginal_options_and_more'),
        ('inventario', '0005_usuario_puede_cambiar_sucursal_usuario_sucursal'),
        ('ordenes_de_trabajo', '0012_alter_ordentrabajo_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso_sri', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de Acceso SRI')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='facturas/xml/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('imagen_factura', models.ImageField(blank=True, null=True, upload_to='facturas/fotos/%Y/%m/')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del proveedor')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='R.U.C.')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de factura')),
                ('clave_acceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de acceso / autorización')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('dias_plazo', models.PositiveIntegerField(default=0, help_text='Ej: 15, 30 días')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vence el')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('esta_pagada', models.BooleanField(default=False, verbose_name='¿Pagada?')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura de compra',
                'verbose_name_plural': 'Facturas de compra',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.RemoveField(
            model_name='facturacompraxml',
            name='proveedor_rel',
        ),
        migrations.AlterModelOptions(
            name='detallefacturanormalizado',
            options={'ordering': ['id'], 'verbose_name': 'Detalle normalizado', 'verbose_name_plural': 'Detalles normalizados'},
        ),
        migrations.AlterModelOptions(
            name='detallefacturaoriginal',
            options={'ordering': ['id'], 'verbose_name': 'Detalle original proveedor', 'verbose_name_plural': 'Detalles originales proveedor'},
        ),
        migrations.AlterModelOptions(
            name='pagoproveedor',
            options={'ordering': ['-fecha_pago', '-id'], 'verbose_name': 'Abono a proveedor', 'verbose_name_plural': 'Abonos a proveedores'},
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='codigo_producto_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_normalizados_compra', to='inventario.codigoproducto'),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='producto_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_normalizados_compra', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detallefacturanormalizado',
            name='nombre_limpio',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre normalizado'),
        ),
        migrations.AlterField(
            model_name='detallefacturaoriginal',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='comprobante_banco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='metodo',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa'], name='compras_pro_empresa_f722f8_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre_contacto'], name='compras_pro_nombre__e46ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['ruc'], name='compras_pro_ruc_e67193_idx'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra', to='compras.proveedor', verbose_name='Proveedor relacionado'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='ordenes_de_trabajo.sucursal', verbose_name='Sucursal destino'),
        ),
        migrations.AlterField(
            model_name='detallefacturaoriginal',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_originales', to='compras.facturacompra'),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='compras.facturacompra'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['fecha_emision'], name='compras_fac_fecha_e_da8747_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['numero_factura'], name='compras_fac_numero__380299_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['clave_acceso_sri'], name='compras_fac_clave_a_f17ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['procesado'], name='compras_fac_procesa_a3c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['sucursal_destino'], name='compras_fac_sucursa_07e829_idx'),
        ),
        migrations.DeleteModel(
            name='FacturaCompraXML',
        ),
    ]
