# Generated by Django 6.0.3 on 2026-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_facturacompra_remove_facturacompraxml_proveedor_rel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tiene_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número en formato internacional. Ej: +593999999999', max_length=30, null=True),
        ),
    ]
