# Generated by Django 6.0.3 on 2026-06-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_proveedor_tiene_whatsapp_proveedor_whatsapp'),
        ('ordenes_de_trabajo', '0045_configuraciontributaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='aplica_iva',
            field=models.BooleanField(default=True, help_text='¿Este ítem grava IVA?'),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='tipo_destino',
            field=models.CharField(choices=[('INVENTARIO', 'Repuesto / Insumo (Suma Stock)'), ('GASTO', 'Gasto Administrativo (Comida, Suministros)'), ('SERVICIO', 'Servicio Externo (Mano de obra, Torno)')], default='INVENTARIO', max_length=20),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='configuracion_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes_de_trabajo.configuraciontributaria'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='porcentaje_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
