# Generated by Django 6.0.3 on 2026-07-13 03:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_detallefacturanormalizado_aplica_iva_and_more'),
        ('inventario', '0012_remove_imagenproducto_codigo_producto_and_more'),
        ('ordenes_de_trabajo', '0047_alter_cotizacioninsumodetalle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(default=1)),
                ('fecha_vencimiento', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Cuota programada',
                'verbose_name_plural': 'Cuotas programadas',
                'ordering': ['factura', 'numero_cuota'],
            },
        ),
        migrations.AlterModelOptions(
            name='detallefacturaoriginal',
            options={'ordering': ['id'], 'verbose_name': 'Detalle original del proveedor', 'verbose_name_plural': 'Detalles originales del proveedor'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['empresa', 'razon_social', 'nombre_contacto'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='actualizar_pvp_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='factura_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_manuales', to='compras.facturacompra'),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='nuevo_precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='orden_trabajo_rel',
            field=models.ForeignKey(blank=True, help_text='Orden de trabajo para la cual se realizó esta compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_relacionadas', to='ordenes_de_trabajo.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detallefacturaoriginal',
            name='aplica_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detallefacturaoriginal',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='detallefacturaoriginal',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detallefacturaoriginal',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'En proceso / Borrador'), ('PROCESADA', 'Registrada en inventario'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='origen_ingreso',
            field=models.CharField(choices=[('XML', 'Subida de XML'), ('CLAVE', 'Clave de acceso SRI'), ('MANUAL', 'Digitación manual')], default='MANUAL', max_length=10, verbose_name='Origen de ingreso'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='sustento_tributario',
            field=models.CharField(default='01', max_length=2, verbose_name='Sustento tributario SRI'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='tipo_comprobante',
            field=models.CharField(default='01', max_length=2, verbose_name='Tipo de comprobante'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='agente_retencion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='obligado_contabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detallefacturanormalizado',
            name='aplica_iva',
            field=models.BooleanField(default=True, help_text='Indica si el detalle grava IVA.'),
        ),
        migrations.AlterField(
            model_name='detallefacturanormalizado',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallefacturanormalizado',
            name='costo_anterior',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='detallefacturanormalizado',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='detallefacturanormalizado',
            name='detalle_original',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_normalizado', to='compras.detallefacturaoriginal'),
        ),
        migrations.AlterField(
            model_name='detallefacturanormalizado',
            name='tipo_destino',
            field=models.CharField(choices=[('INVENTARIO', 'Repuesto / Insumo (suma stock)'), ('GASTO', 'Gasto administrativo'), ('SERVICIO', 'Servicio externo')], default='INVENTARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallefacturaoriginal',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallefacturaoriginal',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='clave_acceso_sri',
            field=models.CharField(blank=True, max_length=49, null=True, unique=True, verbose_name='Clave de acceso SRI'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='configuracion_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='ordenes_de_trabajo.configuraciontributaria'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N.º de factura'),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='metodo',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='detallefacturanormalizado',
            index=models.Index(fields=['tipo_destino'], name='compras_det_tipo_de_6bc074_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturanormalizado',
            index=models.Index(fields=['ingresado_al_inventario'], name='compras_det_ingresa_842cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturanormalizado',
            index=models.Index(fields=['codigo_sistema'], name='compras_det_codigo__d47ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturanormalizado',
            index=models.Index(fields=['codigo_barras'], name='compras_det_codigo__dd6cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturaoriginal',
            index=models.Index(fields=['codigo_proveedor'], name='compras_det_codigo__bd5af6_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturaoriginal',
            index=models.Index(fields=['factura'], name='compras_det_factura_9866af_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['estado'], name='compras_fac_estado_c51c51_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['origen_ingreso'], name='compras_fac_origen__3a954e_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['ruc'], name='compras_fac_ruc_9dbc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['fecha_pago'], name='compras_pag_fecha_p_b55928_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['metodo'], name='compras_pag_metodo_aa00f8_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['razon_social'], name='compras_pro_razon_s_29891d_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['activo'], name='compras_pro_activo_ba1512_idx'),
        ),
        migrations.AddConstraint(
            model_name='detallefacturanormalizado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('detalle_original__isnull', False), ('factura_manual__isnull', True)), models.Q(('detalle_original__isnull', True), ('factura_manual__isnull', False)), _connector='OR'), name='compras_detalle_normalizado_un_solo_origen'),
        ),
        migrations.AddConstraint(
            model_name='facturacompra',
            constraint=models.UniqueConstraint(condition=models.Q(('ruc__isnull', False), ('numero_factura__isnull', False)), fields=('ruc', 'numero_factura'), name='compras_factura_ruc_numero_unicos'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('ruc__isnull', False)), fields=('ruc',), name='compras_proveedor_ruc_unico_no_nulo'),
        ),
        migrations.AddField(
            model_name='cuotapago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='compras.facturacompra'),
        ),
        migrations.AddConstraint(
            model_name='cuotapago',
            constraint=models.UniqueConstraint(fields=('factura', 'numero_cuota'), name='compras_cuota_numero_unico_por_factura'),
        ),
    ]
