# Generated by Django 6.0.3 on 2026-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_cuotapago_alter_detallefacturaoriginal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='codigo_origen',
            field=models.CharField(blank=True, db_index=True, help_text='Código exactamente como llegó desde el proveedor o como fue digitado manualmente.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallefacturanormalizado',
            name='descripcion_origen',
            field=models.CharField(blank=True, help_text='Descripción original del proveedor antes de que el usuario la normalice o vincule al inventario.', max_length=255, null=True),
        ),
    ]
