# Generated by Django 6.0.3 on 2026-08-02 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_de_trabajo', '0049_ordentrabajo_intervalo_mantenimiento_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPruebaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('pregunta', models.CharField(max_length=250)),
                ('permite_observacion', models.BooleanField(default=True)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta de prueba de ruta',
                'verbose_name_plural': 'Preguntas de prueba de ruta',
                'ordering': ['orden_visual', 'pregunta'],
            },
        ),
        migrations.CreateModel(
            name='AvaluoMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_avaluo', models.CharField(blank=True, db_index=True, editable=False, max_length=30, null=True, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], db_index=True, default='BORRADOR', max_length=15)),
                ('resultado_general', models.CharField(choices=[('SIN_DEFINIR', 'Sin definir'), ('BUEN_ESTADO', 'Vehículo en buen estado'), ('MANTENIMIENTO', 'Requiere mantenimiento'), ('REPARACION_MENOR', 'Requiere reparación menor'), ('REPARACION_MAYOR', 'Requiere reparación mayor'), ('NO_RECOMENDABLE', 'No recomendable')], default='SIN_DEFINIR', max_length=30)),
                ('solicitado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_avaluo', models.DateField(default=django.utils.timezone.localdate)),
                ('numero_orden_respaldo', models.CharField(blank=True, max_length=50, null=True)),
                ('sucursal_respaldo', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente_respaldo', models.CharField(blank=True, max_length=200, null=True)),
                ('identificacion_cliente_respaldo', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono_cliente_respaldo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_cliente_respaldo', models.TextField(blank=True, null=True)),
                ('placa_respaldo', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('marca_respaldo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_respaldo', models.CharField(blank=True, max_length=250, null=True)),
                ('vehiculo_respaldo', models.CharField(blank=True, max_length=250, null=True)),
                ('anio_modelo_respaldo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color_respaldo', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometraje_respaldo', models.PositiveIntegerField(blank=True, null=True)),
                ('chasis_respaldo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('cilindraje', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_transmision', models.CharField(choices=[('NO_DEFINIDA', 'No definida'), ('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('CVT', 'CVT'), ('DOBLE_EMBRAGUE', 'Doble embrague'), ('OTRA', 'Otra')], default='NO_DEFINIDA', max_length=20)),
                ('aire_acondicionado', models.BooleanField(blank=True, null=True)),
                ('vidrios_electricos', models.BooleanField(blank=True, null=True)),
                ('alarma', models.BooleanField(blank=True, null=True)),
                ('aros', models.BooleanField(blank=True, null=True)),
                ('radio', models.BooleanField(blank=True, null=True)),
                ('cierre_centralizado', models.BooleanField(blank=True, null=True)),
                ('ruido_motor_otros', models.TextField(blank=True, null=True)),
                ('diagnostico_general', models.TextField(blank=True, null=True)),
                ('reparaciones_recomendadas', models.TextField(blank=True, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('aplica_vehiculo_usado', models.BooleanField(default=False)),
                ('recibido_como_parte_pago_de', models.CharField(blank=True, max_length=250, null=True)),
                ('vendedor_que_solicita', models.CharField(blank=True, max_length=200, null=True)),
                ('anio_matricula', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anio_modelo_usado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cilindraje_usado', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva_dominio', models.BooleanField(blank=True, null=True)),
                ('color_usado', models.CharField(blank=True, max_length=50, null=True)),
                ('propietario', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_propietario', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_propietario', models.TextField(blank=True, null=True)),
                ('identificacion_propietario', models.CharField(blank=True, max_length=30, null=True)),
                ('avaluo_comercial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_recepcion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_reparacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('firma_evaluador', models.ImageField(blank=True, null=True, upload_to='avaluos/firmas/evaluadores/%Y/%m/')),
                ('firma_responsable', models.ImageField(blank=True, null=True, upload_to='avaluos/firmas/responsables/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaluos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaluos_creados', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaluos_evaluados', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador del taller')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='avaluo_mecanico', to='ordenes_de_trabajo.ordentrabajo', verbose_name='Orden de trabajo')),
                ('responsable_taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaluos_responsable_taller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avalúo mecánico',
                'verbose_name_plural': 'Avalúos mecánicos',
                'ordering': ['-fecha_avaluo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompresionCilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cilindro', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unidad', models.CharField(choices=[('PSI', 'PSI'), ('BAR', 'Bar'), ('KPA', 'kPa')], default='PSI', max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('avaluo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compresiones_motor', to='avaluos.avaluomecanico')),
            ],
            options={
                'verbose_name': 'Compresión de cilindro',
                'verbose_name_plural': 'Compresiones de cilindros',
                'ordering': ['numero_cilindro'],
            },
        ),
        migrations.CreateModel(
            name='FotoAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avaluos/fotos/%Y/%m/')),
                ('tipo_foto', models.CharField(choices=[('FRONTAL', 'Parte frontal'), ('POSTERIOR', 'Parte posterior'), ('LATERAL_IZQUIERDO', 'Lateral izquierdo'), ('LATERAL_DERECHO', 'Lateral derecho'), ('MOTOR', 'Motor'), ('INTERIOR', 'Interior'), ('TABLERO', 'Tablero'), ('KILOMETRAJE', 'Kilometraje'), ('CHASIS', 'Chasis / VIN'), ('MATRICULA', 'Matrícula'), ('DANIO', 'Daño encontrado'), ('DOCUMENTO', 'Documento'), ('OTRA', 'Otra')], default='OTRA', max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('avaluo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='avaluos.avaluomecanico')),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos_avaluos_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fotografía del avalúo',
                'verbose_name_plural': 'Fotografías del avalúo',
                'ordering': ['orden_visual', 'fecha_subida', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspeccionAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('EXTERIOR', 'Apariencia exterior'), ('INTERIOR', 'Apariencia interior'), ('MECANICA', 'Revisión mecánica'), ('ELECTRICO', 'Sistema eléctrico'), ('FRENOS', 'Sistema de frenos'), ('OTROS', 'Otros')], db_index=True, max_length=20)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ítem de inspección',
                'verbose_name_plural': 'Ítems de inspección',
                'ordering': ['seccion', 'orden_visual', 'nombre'],
                'indexes': [models.Index(fields=['seccion', 'activo', 'orden_visual'], name='avaluo_item_seccion_idx')],
                'constraints': [models.UniqueConstraint(fields=('seccion', 'nombre'), name='avaluo_item_seccion_nombre_unico')],
            },
        ),
        migrations.CreateModel(
            name='ItemRevisionSiNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('PARTICULAS_FUGAS', 'Partículas y fugas'), ('MOTOR', 'Motor'), ('FLUIDOS', 'Fluidos'), ('OTROS', 'Otros')], default='PARTICULAS_FUGAS', max_length=30)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ítem de revisión Sí/No',
                'verbose_name_plural': 'Ítems de revisión Sí/No',
                'ordering': ['seccion', 'orden_visual', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('seccion', 'nombre'), name='avaluo_revision_sino_nombre_unico')],
            },
        ),
        migrations.CreateModel(
            name='ResultadoInspeccionAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NO_REVISADO', 'No revisado'), ('NRR', 'No requiere reparación'), ('RRM', 'Requiere reparación menor'), ('RRT', 'Requiere reparación total')], default='NO_REVISADO', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('avaluo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_inspeccion', to='avaluos.avaluomecanico')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='avaluos.iteminspeccionavaluo')),
            ],
            options={
                'verbose_name': 'Resultado de inspección',
                'verbose_name_plural': 'Resultados de inspección',
                'ordering': ['item__seccion', 'item__orden_visual', 'item__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoPruebaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('NO_REVISADO', 'No revisado'), ('SI', 'Sí'), ('NO', 'No'), ('NO_APLICA', 'No aplica')], default='NO_REVISADO', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('avaluo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_prueba_ruta', to='avaluos.avaluomecanico')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='avaluos.itempruebaruta')),
            ],
            options={
                'verbose_name': 'Resultado de prueba de ruta',
                'verbose_name_plural': 'Resultados de prueba de ruta',
                'ordering': ['item__orden_visual', 'item__pregunta'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoRevisionSiNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('NO_REVISADO', 'No revisado'), ('SI', 'Sí'), ('NO', 'No'), ('NO_APLICA', 'No aplica')], default='NO_REVISADO', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('avaluo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_revision_sino', to='avaluos.avaluomecanico')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='avaluos.itemrevisionsino')),
            ],
            options={
                'verbose_name': 'Resultado de revisión Sí/No',
                'verbose_name_plural': 'Resultados de revisión Sí/No',
                'ordering': ['item__seccion', 'item__orden_visual'],
            },
        ),
        migrations.AddIndex(
            model_name='avaluomecanico',
            index=models.Index(fields=['estado', 'fecha_avaluo'], name='avaluo_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='avaluomecanico',
            index=models.Index(fields=['placa_respaldo', 'fecha_avaluo'], name='avaluo_placa_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='avaluomecanico',
            index=models.Index(fields=['evaluador', 'estado'], name='avaluo_eval_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='compresioncilindro',
            constraint=models.UniqueConstraint(fields=('avaluo', 'numero_cilindro'), name='avaluo_compresion_cilindro_unico'),
        ),
        migrations.AddIndex(
            model_name='fotoavaluo',
            index=models.Index(fields=['avaluo', 'tipo_foto'], name='avaluo_foto_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoinspeccionavaluo',
            index=models.Index(fields=['avaluo', 'estado'], name='avaluo_resultado_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultadoinspeccionavaluo',
            constraint=models.UniqueConstraint(fields=('avaluo', 'item'), name='avaluo_resultado_item_unico'),
        ),
        migrations.AddConstraint(
            model_name='resultadopruebaruta',
            constraint=models.UniqueConstraint(fields=('avaluo', 'item'), name='avaluo_prueba_ruta_item_unico'),
        ),
        migrations.AddConstraint(
            model_name='resultadorevisionsino',
            constraint=models.UniqueConstraint(fields=('avaluo', 'item'), name='avaluo_revision_sino_item_unico'),
        ),
    ]
