# Generated by Django 6.0.3 on 2026-08-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaluomecanico',
            name='aire_acondicionado',
        ),
        migrations.RemoveField(
            model_name='avaluomecanico',
            name='alarma',
        ),
        migrations.RemoveField(
            model_name='avaluomecanico',
            name='aros',
        ),
        migrations.RemoveField(
            model_name='avaluomecanico',
            name='cierre_centralizado',
        ),
        migrations.RemoveField(
            model_name='avaluomecanico',
            name='radio',
        ),
        migrations.RemoveField(
            model_name='avaluomecanico',
            name='vidrios_electricos',
        ),
        migrations.CreateModel(
            name='CategoriaEquipamientoAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de equipamiento',
                'verbose_name_plural': 'Categorías de equipamiento',
                'ordering': ['orden_visual', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'orden_visual'], name='aval_cat_equip_act_ord_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipamientoAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('permite_observacion', models.BooleanField(default=True)),
                ('orden_visual', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamientos', to='avaluos.categoriaequipamientoavaluo')),
            ],
            options={
                'verbose_name': 'Equipamiento de avalúo',
                'verbose_name_plural': 'Equipamientos de avalúo',
                'ordering': ['categoria__orden_visual', 'categoria__nombre', 'orden_visual', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEquipamientoAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presencia', models.CharField(choices=[('NO_REVISADO', 'No revisado'), ('SI', 'Sí tiene'), ('NO', 'No tiene')], db_index=True, default='NO_REVISADO', max_length=15)),
                ('funcionamiento', models.CharField(choices=[('NO_REVISADO', 'No revisado'), ('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No funciona'), ('NO_APLICA', 'No aplica')], db_index=True, default='NO_REVISADO', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('avaluo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_equipamiento', to='avaluos.avaluomecanico')),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='avaluos.equipamientoavaluo')),
            ],
            options={
                'verbose_name': 'Resultado de equipamiento',
                'verbose_name_plural': 'Resultados de equipamiento',
                'ordering': ['equipamiento__categoria__orden_visual', 'equipamiento__categoria__nombre', 'equipamiento__orden_visual', 'equipamiento__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='equipamientoavaluo',
            index=models.Index(fields=['categoria', 'activo', 'orden_visual'], name='aval_equip_cat_act_ord_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipamientoavaluo',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='aval_equip_categoria_nombre_unico'),
        ),
        migrations.AddIndex(
            model_name='resultadoequipamientoavaluo',
            index=models.Index(fields=['avaluo', 'presencia'], name='aval_res_equip_pres_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoequipamientoavaluo',
            index=models.Index(fields=['avaluo', 'funcionamiento'], name='aval_res_equip_func_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultadoequipamientoavaluo',
            constraint=models.UniqueConstraint(fields=('avaluo', 'equipamiento'), name='aval_resultado_equipamiento_unico'),
        ),
    ]
